### ISSUE TITLE
Add SNMP page counter and printer status support to socket and lpd backends

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#1655]
Version: 1.4-feature
CUPS.org User: mike

Update the socket and lpd backends to query the page counter and status bits.  Will also need to add SNMP options and advertising of those options from the SNMP backend.

The status is stored in:

```
HOST-RESOURCES-MIB::hrPrinterStatus.1 (idle(3), printing(4), warmup(5))
(1.3.6.1.2.1.25.3.5.1.1.1)
HOST-RESOURCES-MIB::hrPrinterDetectedErrorState.1 (bits for lowPaper, noPaper, lowToner, noToner, doorOpen, jammed, offline)
(1.3.6.1.2.1.25.3.5.1.2.1)
```

**Comment by AnilPujar2014** [comment]
https://www.ietf.org/rfc/rfc1759.txt

In this Link: If you see the description: Its confusing. Please help which is right?

if you scroll to page 15 for the above shared link, you will find the below description: Which is confusing.

hrPrinterStatus OBJECT-TYPE
          SYNTAX INTEGER {
              other(1),
              unknown(2),
              idle(3),
              printing(4),
              warmup(5)
          }
          ACCESS read-only
          STATUS mandatory
          DESCRIPTION
                  "The current status of this printer device.  When
                  in the idle(1), printing(2), or warmup(3) state,
                  the corresponding hrDeviceStatus should be
                  running(2) or warning(3).  When in the unknown
                  state, the corresponding hrDeviceStatus should be
                  unknown(1)."
          ::= { hrPrinterEntry 1 }

Syntax Integer result value is different from the description.

What is "other(1)" meaning, since i'm getting response as 1. Is it is Idle or Other?

**Comment by michaelrsweet** [comment]
@AnilPujar2014 Please use [RFC 3805](https://tools.ietf.org/html/rfc3805) as RFC 1759 is obsolete. The updated RFC corrects the description of this property.
