### ISSUE TITLE
Implement the --version and --help options in the cups tools

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2930]
Version: -feature
CUPS.org User: stefano

Most UNIX/commandline users expect to see these options supported, and indeed they are some of the first command they'll try when they are experimenting with a new command.

--help usefulness is obvious, while --version is useful for example for issuing output for showing to others problems.

Implementation should be fairly easy, so this is that type of issue which could be targeted by a "cups-love" task.

Regards.

**Comment by michaelrsweet** [comment]
After review we have decided not to address this issue.

**Comment by imsedgar** [comment]
Even issues with very useful requests are closed as "we have decided not to address this issue". That is very bad!
Even if mac programs don't have a --version and --help option because users are expected not to use command line in mac (...?) and it is not easy to find documentation for many mac command line tools, it would be so (very!) simple to add --version and --help options...

I cannot understand that someone can  decline this.

**Comment by michaelrsweet** [comment]
Edgar, this bug has been sitting in the queue for 9 years, we don't have the resources to fix every bug, most users access CUPS through a GUI, and adding these options also means adding localization changes to every program.

Feel free to do a pull request with the necessary changes...
