### ISSUE TITLE
lp: page selection with -P processed after number-up

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3008]
Version: 1.3.9
CUPS.org User: martin.pitt.canonical

From http://bugs.debian.org/501311:

------ snip -------
  lp -P 41-51 -o number-up=2 file.pdf

I expected it to extract pp. 41-51 from file.pdf, then convert them to
2up and send it to the printer.

I can think of two fixes:
1. In the description of the -P switch in the 'lp' manpage, explain
   that the page numbers are those after page rearrangements.
2. Change the cups filters to first select pages with -P, then
   rearrange pages.

The first fix clarifies the situation but makes it hard to use -P
with number-up, so I like the second fix.
------ snip -------

I confirmed the issue with 1.3.9.

**Comment by archenemies** [comment]
@michaelrsweet said "IPP specifies the page-ranges applies after imposition, so the current implementation is correct."...

Where does IPP specify that page-ranges applies after number-up processing? I'm looking at

https://tools.ietf.org/html/rfc2566#section-4.2.7

and don't see it...

Anyway, this is super counter-intuitive. If it is really what the spec says, then it would be nice to also have an option like input-page-ranges which would allow users to select pages from the actual document.

**Comment by michaelrsweet** [comment]
You want to look at RFC 2911 - RFC 2566 (IPP/1.0) is OBSOLETE and experimental.

**Comment by archenemies** [comment]
Thank you. Now, I'm looking at this:

https://tools.ietf.org/html/rfc2911#section-4.2.7

I don't see what you were referring to (back in 2008!).

In fact, [section 15.3](https://tools.ietf.org/html/rfc2911#section-15.3) says this:

      2. The document data is in the form of a print-stream in a known
         media type. The "page-ranges" attribute is used to select, as
         specified in section 4.2.7, a sub-sequence of the pages in the
         print-stream that are to be processed and images.

      3. The input to this step is a sequence of print-stream pages.
         This step is controlled by the "number-up" attribute. If the
         value of "number-up" is N, then during the processing of the
         print-stream pages, each N print-stream pages are positioned,
         as specified in section 4.2.9, to create a single impression.

I think the words "the input to this step" mean "the input to step 3", since steps are being numbered. I guess step 3 could be described as taking pages and turning them into "impressions". Impressions are sent to the printer and put on pages, but a single impression might contain multiple document pages. The way I read this, applying the "page-ranges" option (in step 2) takes the user-supplied range arguments and uses them to select numbered document pages (from the formatting step, step 1) not impressions (from step 3)...

**Comment by archenemies** [comment]
@michaelrsweet - I didn't mean to scare you away with my interpretation of RFC 2911. I was just trying to help us both figure out where you were coming from... Were we looking at different documents? Different parts of the same document? Thank you.
