### ISSUE TITLE
State information belongs in /var/lib/cups, not /etc/cups

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3067]
Version: 1.3.9
CUPS.org User: lamont

Section 5 of the FHS describes the /var hierarchy, and notes that /var/lib is for "Variable State Information"

"
Purpose

This hierarchy holds state information pertaining to an application or the
system. State information is data that programs modify while they run, and that
pertains to one specific host. Users must never need to modify files in /var/
lib to configure a package's operation.

State information is generally used to preserve the condition of an application
(or a group of inter-related applications) between invocations and between
different instances of the same application. State information should generally
remain valid after a reboot, should not be logging output, and should not be
spooled data."
Looking at /etc/cups/printers.conf, the following variables appear to be State, and _NOT_ configuration:

State
StateTime
StateMessage

The timestamp in the '@ Written by cupsd on YYYY-MM-DD...' line is also far more state-like than configuration, unless the timestamp is specifically because of user configuration changes.

Similar logic can be applied to the other files.

**Comment by ckotte** [comment]
Why isn't it possible to move State, StateTime, Attribute marker-levels and Attribute marker-change-time from /etc/cups/printers.conf to another file to /var/lib/? It's about the current state of the printer and not about the configuration?

**Comment by imsedgar** [comment]
I confirm that according to Filesystem Hierarchy Standard (FHS) /etc is for (static) configuration files. Administrators can store their configuration files there. Status information like printer state, jobs, dynamic (variable) values like attributes requested from the printer should be stored in a subdirectory of /var, if the information should still be available after a reboot, or a subdirectory of /run (e.g. /run/cups), if the information does not make sence after a reboot (like file or process locks). (/var/run on Fedora is a symlink to /run.)

Fedora cups package already uses some directories in /var:

# rpm -ql cups|grep /var
/var/log/cups
/var/run/cups
/var/run/cups/certs
/var/spool/cups
/var/spool/cups/tmp

But there is no subdirectory like /var/lib/cups for status information. Files like subscriptions.conf, printers.conf, maybe subdirectory ppd too, or at least the dynamic parts of these files, should go to files in /var or /run. /etc should not be modifies by services on a regular basis, only if the administrator requests configuration changes.

I think also the (dynamic) list of printers and there configuration can be stored in something like /var/lib/cups, as long a these files are only written by cups (and cups supplement services like cups-browsed).

**Comment by ckotte** [comment]
Does the state information need to be user-editable? It's just about this information and not about the configuration which should stay in /etc. Just move that state information to /var/lib and everyone is happy.

**Comment by imsedgar** [comment]
Dear Michael,

I think it is a principal design problem to use the same file for user editing the configuration and updates by program. This results in the classic problem with simultaneous writers and readers where one  change / write may be lost in some situations.

I see no good reason to mix printer configuration files with status information files, except that your program need to know which information it should read and write to which file. cups need to open some more file (one if it uses a status file for all printers, or more if one file for each printer), and the code needs to be adapted for this change. But that's all.

The advantage would be that configuration files in /etc/cups can be read-only for cups itself, and in can watch for changes and merge them into the runtime configuration, and / or read them at startup. There will be no problem any more if an administrator changes the file while cups is running. Even may cups change the configuration file if an administrator wants to set a configuration option by cli (e.g. lpadmin) or web interface instead of editing the files, that does not contradict the separation of status information.

I only see advantages in separating configuration files and state and dynamic configuration files - apart of the fact, that cups code needs to be changed. Which disadvantages do you see?

**Comment by michaelrsweet** [comment]
Folks, we are not changing how things work in the current implementation of cupsd after 20 years.

In the future, when we make major architectural changes (and those are coming), we will revisit how printer configuration and state information is stored, and take into account all of the various filesystem "standards" that exist.
