### ISSUE TITLE
Generate self-signed certificate at start-up?

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3618]
Version: -feature
CUPS.org User: twaugh.redhat

When a client first connects to a new CUPS scheduler over an encrypted connection, there is a long delay while the scheduler creates a self-signed certificate.

This can cause some clients (especially samba) to time out.

Would you consider a change that would cause the certificate to be generated as soon as the scheduler starts?

**Comment by michaelrsweet** [comment]
@troy-mac On Linux just put the PEM-encoded certificate (servername.crt) and private key (servername.key) in /etc/cups/ssl. The files cannot have passwords on them.

On macOS add the cert and private key to the system keychain.

**Comment by troy-mac** [comment]
Hi Michael,  thanks so much for replying so quickly,  I have the certs in the /etc/cups/ssl directory, but when going to my cups server via web browser I still receive the ssl error because it is defaulting to the self signed servername cert.  I have tried changing the cupsd_conf file to listen on 443 etc... but no luck.  no matter what I have done it always defaults to the self signed cert.   Perhaps I am looking at this wrong? will the administrator web page always default to the self signed? 

Thanks again!

-Troy

**Comment by michaelrsweet** [comment]
@troy-mac What OS and version of CUPS?

**Comment by troy-mac** [comment]
Ubuntu and Cups 2.1.3 default install for Ubuntu.

**Comment by troy-mac** [comment]
I think I now have it working,  I had to put it behind and AWS ELB and added these back into the config and it seems to be working `SSLPort 443
SSLListen 0.0.0.0:443
Listen 0.0.0.0:631
Listen /var/run/cups/cups.sock`
