### ISSUE TITLE
Choosing to print only odd pages with 2 pages per side doesn't work

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3694]
Version: 1.4.3
CUPS.org User: Futterwaken

I'm not sure if this bug should be reported here...
#### The Problem

If you choose to print 2 pages per side and select to print just the odd pages, the system does the following:
Print page 1 and page 2 of the document side by side,
Then pages 5 and 6
Then pages 9 and 10
And so forth...

If you then choose to print just the even pages you get the complimentary result:
Pages 3 and 4
Then pages 7 and 8
And so forth...

===Notice that I get odd and even pages but it skips every other pair===
#### What's going on

So what happens is that the result is composed with the odd and even pages of the original document and then this result gets filtered out such that if you select just odd pages, it gives you just odd pages of the result, not the original document.
#### What should it do

I believe that when the user picks up an option to print just odd pages (or even pages) the system should apply that filter along with the selected range of pages in the first place, only then these pages should be composed side by side (or 4  in one side or whatever).
#### Original scenario

I was trying to print a 400 page manual of a Texas instruments calculator.
I wanted to print two pages on each side of a A4 sized piece of paper, totalling 4 pages at A5 size in one piece of paper.
Also, I wanted to match the front side of the paper with the back side so that if the front had page 1, the back had to have page 2.
I hoped by combining front/back as pages 1/2, 3/4, 5/6, and so forth, that in the end I could cut the printed papers and make a book...
But if pages 1 and 2 get printed on the same face of the same piece of paper how can they ever be printed back to back???
I tried various workarounds with no success.
(we also should be able to select "odd" pages or "even" pages in page range and "-odd"/"-even" to get them in the reverse order).
The only working solutions involve the rearrangement of pages of the original document prior to the printing request.
#### How did I get through it

In the end (this make me sad) I end up doing the job on my laptop which has Windows 7 and features similar printing options, only they do what you expect.

Regards,

Futterwaken

**Comment by archenemies** [comment]
> This behaves correctly according to the requirements of IPP.

See #4837 and https://github.com/apple/cups/issues/3008#issuecomment-222032365.

I wanted to clarify the closure of this bug in case someone else stumbles upon it. It's actually in violation of IPP (and common sense) but Michael Sweet argued somewhere (I can't find where) that very few users use these options on Mac systems, so it's not worth fixing. My feeling is that perhaps the options are not often used because they don't work properly; and besides that we should work towards eventually having properly functioning software (even if this takes years to achieve).

**Comment by michaelrsweet** [comment]
@archenemies There is no standard IPP attribute for printing even or odd numbered pages, so the semantics as implemented by CUPS are correct - we defined them!

As for the interaction between the "number-up" and "page-ranges" attributes, we have acknowledged the issue but if we "fix" the interpretation then we will break existing clients and software that depend on behavior that has existed in CUPS since v1.0.

**Comment by archenemies** [comment]
In IPP, as I recall, the flat rectangular entities which are created after processing "number-up" are called "impressions" and not "pages". So even if the functionality of selecting even or odd numbered pages is not part of the IPP spec, it should result in what the user is requesting, not what CUPS has implemented "according to the requirements of IPP".

In this case I can see how some users would prefer the current behavior, for example if printing a manual duplex run of a document with 2-up pages. But it should also be possible to get the more intuitive behavior that this user requested.

Regarding number-up/page-ranges - I understand the desire to preserve backwards compatibility - and I agree strongly that we should do so. But I seem to recall you arguing earlier that it was impossible to change the number-up/page-ranges interaction because apparently it involves logic which has been copy-pasted into a huge number of PPDs or filters or something, and it would be difficult to change them all at once. However, if the main obstacle is now backwards compatibility then I would advocate creating some new syntax which can allow users to get the correct/desired behavior without breaking existing applications. I can suggest such an option syntax if you like.

**Comment by michaelrsweet** [comment]
Per RFC 8011, "number-up" and "page-ranges" apply to input pages, which are imposed to create impressions which are printed on media sheets. Hopefully we've clarified this over RFC 2911, since many implementations have messed up on this, not just CUPS... :/

The CUPS "page-set" attribute semantics are really "impression-set", meaning it selects a set of impressions specifically to support things like manual duplex. And this is one of the reasons why it hasn't been adopted as a standard IPP extension...

**Comment by archenemies** [comment]
Thank you for clarifying regarding the RFC. That's pretty much what I was trying to say, but it's good to know that we're on the same page (so to speak!). When you said "according to the requirements of IPP" earlier, it made it sound like you were claiming that the behavior of CUPS was specified by the standards, and I just wanted to point out that this is not the case here.

Here is the part of my message which you haven't addressed yet, should you care to do so:

> ... But it should also be possible to get the more intuitive behavior that this user requested.

> Regarding number-up/page-ranges - I understand the desire to preserve backwards compatibility - and I agree strongly that we should do so. But I seem to recall you arguing earlier that it was impossible to change the number-up/page-ranges interaction because apparently it involves logic which has been copy-pasted into a huge number of PPDs or filters or something, and it would be difficult to change them all at once. However, if the main obstacle is now backwards compatibility then I would advocate creating some new syntax which can allow users to get the correct/desired behavior without breaking existing applications. I can suggest such an option syntax if you like.

**Comment by michaelrsweet** [comment]
While I appreciate wanting to provide alternate functionality for page range selection, I don't think we will be introducing a new attribute that implements the original IPP semantics with new names. Aside from causing a great deal of confusion, it will be an implementation/interoperability nightmare.
