### ISSUE TITLE
cups-lpd hugh jobs (>2G) fail

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4351]
Version: 1.4.6
CUPS.org User: mgoppold

real hugh jobs (more than 2147483647 bytes) can not print via cups-lpd because of int type of looping var.
error message sever side: Trailing character after file is not nul (48)!

**Comment by yurashek** [comment]
Hi Michael,
As I mentioned in my last comment the problem is not fixed on LP32 platforms yet because ssize_t (unsigned 32bit on LP32) counter can not  count over 4G.  ...well 4G is a bit better than 2G but the fix proposed by me extended the length to "long long" (signed 64bit) count which can be assumed as a fix.

Can you back-out this change (I was peeking into cups-2.1.4 source) and replace it by the fix sent by me please? My fix is tested (in lab) and it is really not effortless to arrange test of 4G+ file sent over the lpd on LP32 release.

A bit of "boring" theory:
(s)size_t is intended to be used as a byte-count of *memory* objects so on LP32 will be 32bits long!!!
If you want to avoid of using of generic types (long long)  ....for any reason  ...you can use "offset_t" (man: llseek()) which is more appropriate.

**Comment by michaelrsweet** [comment]
long long is not portable, so no I cannot use your "fix".

LPD is a legacy protocol and support will likely be removed in a future release of CUPS anyways. You should be focusing on moving to IPP which DOES support print files larger than 4GB.
