### ISSUE TITLE
Updating CUPS in OS X El Capitan

### ISSUE THREAD

**Issue by j2m2** [apple/cups#4819]
Hi,

I'm using the last version of OS X El Capitan (10.11.4) and I'm trying to update CUPS from 2.1.0 to the last version of CUPS.

I received "Operation not permitted" in the last step: make install.
I tried with "sudo make install" and I receive the same error.  

Log:
`Making all in cups...
Installing data files in cups...
Installing data files in test...
Installing sample ipptool files in /usr/share/cups/ipptool...
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10701#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10708#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10715#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10722#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10729#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10736#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10743#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10750#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10757#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10764#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10771#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10778#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10785#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10792#: Operation not permitted
/Users/Mendes/Downloads/Zebra/cups-release-2.1.3/install-sh: line 66: /usr/share/cups/ipptool/#inst.10799#: Operation not permitted
make[1]: *** [install-data] Error 1
make: *** [install-data] Error 1
`
Thank you

**Comment by michaelrsweet** [comment]
Short answer: you need to disable SIP (system integrity protection aka rootless) to do this, which I do not recommend.

Long answer: system files are protected in El Capitan and cannot normally be replaced. Also, installing your own CUPS on OSX is completely unsupported and /will/ cause problems since some applications require signed libraries to function. You can, of course, sign the cups files yourself but that isn't something the makefiles can do for you... Finally, software updates including cups will likely yield a system that won't boot due to the mix of CUPS versions...

Why do you want to install a newer version of CUPS? All security and serious bug fixes are already there.
