### ISSUE TITLE
Issue with rpm -V verification and directory/file permissions

### ISSUE THREAD

**Issue by jimkeairns** [apple/cups#4827]
I am working on a project to gain DoD validation for a Linux node running CUPS but with the permissions of files and folders changing when CUPSD starts I can't get it done. If anyone can provide the files and folders that are installed as part of the RPM but may be changed by the application I can get an exception. Does anyone have this info? These are the ones in question.
/etc/cups			RPM = root:root	As Installed = root:lp
/etc/cups/cupsd.conf		RPM = root:root	As Installed = root:lp
/etc/cups/ppd			RPM = root:root 	As Installed = root:lp
/etc/cups/ssl			RPM = root:root 	As Installed = root:lp
/var/cache/cups		RPM = root:root 	As Installed = root:lp
/var/cache/cups/rss		RPM = root:sys 		As Installed = root:lp
/var/run/cups			RPM = root:root 	As Installed = root:lp
/var/spool/cups			RPM = lp:sys		As Installed = root:lp
/var/spool/cups/tmp		RPM = lp:sys		As Installed = root:lp

**Comment by jsmeix** [comment]
cupsd adjusts owner and permissions according to its built-in settings.

When making a RPM package one can specify that cupsd built-in values via appropriate "configure" options like
<pre>
--with-cups-user=lp --with-cups-group=lp
</pre>
and accordinly one must specify in the files section of the RPM spec file to let install rom that files with matching owner and permissions like
<pre>
%config(noreplace) %attr(640,root,lp) %{_sysconfdir}/cups/cupsd.conf
</pre>
so that rpm installs the files with owner and permissions that match what was built-in into cups.

Therefore:
Contact those wherefrom you got the RPM package to get it fixed there.

To adjust the built-in defaults in cupsd, see
http://cups.org/documentation.php/doc-2.1/man-cups-files.conf.html

**Comment by michaelrsweet** [comment]
Where are you getting your RPM from? Are you using the spec file bundled with the CUPS sources or ???

As @jsmeix mentions above, you might need to tweak the spec file to get the permissions to match, although the default spec file we supply *should* be sufficient (if not that is something we will fix).

**Comment by jimkeairns** [comment]
Thank you all for your quick response. I believe the issue is with the way we built the RPMs and not with the default spec file. I will research and get the team that built them to correct.

**Comment by jsmeix** [comment]
FYI:
As an example for a RPM spec file for CUPS
you may have a look at the openSUSE cups.spec file

https://build.opensuse.org/package/view_file/Printing/cups/cups.spec?expand=1
