### ISSUE TITLE
Drop CLA and relicense under BSD/Apache

### ISSUE THREAD

**Issue by KAMiKAZOW** [apple/cups#4845]
Please ask your bosses to adopt Swift/WebKit-style licensing and contributing for CUPS as well, i.e. no CLA/Copyright Assignment and no weird "GPLv2 for everybody but Apple" licensing.

**Comment by michaelrsweet** [comment]
Sorry, that ship sailed about 18 years ago.

**Comment by KAMiKAZOW** [comment]
WebKit.org and Swift.org did not exist 18 years ago.

Did you already ask your boss and got a reply within one hour?

**Comment by michaelrsweet** [comment]
CUPS has existed publicly since 1998. This is the CUPS project, not WebKit or Swift.

As for "talking with my boss", this *has* been discussed many times, in particular when I sold CUPS to Apple in 2007, and the consensus has been that we keep CUPS licensed under GPL2/LGPL2. So I don't need to talk to anyone - we are not changing how CUPS is licensed nor the contributor's agreement.
