### ISSUE TITLE
Wine breaks after upgrading cups

### ISSUE THREAD

**Issue by Sworddragon** [apple/cups#4867]
I'm using Ubuntu 16.10 dev and after upgrading libcups2 and libcupsimage2 from version 2.1.3 to version 2.2 RC1 I'm noticing that Wine does often hang after executing an application (and also on creating a new profile) which I have already reported on the upstream tracker here: https://bugs.winehq.org/show_bug.cgi?id=41131
But on doing some tests I could track this down to the cups upgrade.

**Comment by michaelrsweet** [comment]
There is nothing in CUPS that should cause this - sounds like cupsd isn't setup properly with systemd, or the service isn't enabled/started?

I'd start with the Ubuntu folks...

**Comment by Sworddragon** [comment]
I'm using not the cupsd service but only the libraries to resolve dependencies of packages. A bug in these libraries could indeed cause weird behavior in applications that make use of them.

**Comment by michaelrsweet** [comment]
You haven't provided any information that would lead to a conclusion that the problem is in the CUPS libraries, or indeed in CUPS at all.

Like I said, start by contacting the Ubuntu folks who actually package (and make significant changes to) CUPS for their OS. Do some legwork to isolate a specific cause so that we have something actionable here (if it turns out to be CUPS at all). We do not provide support for WIne or Ubuntu, so unless you can point to a specific change in CUPS that is causing a problem there is nothing we can do to help you.
