### ISSUE TITLE
Document handling of SSL/TLS certificates on Linux/with GNU TLS

### ISSUE THREAD

**Issue by hardfalcon** [apple/cups#4876]
Right now, handling of certificates in CUPS is kinda broken:

- There is no possibility to specify a *file* containing the exact certificate or private key that youu want to use. Instead, you can only specify a directory, to which cups will then append the hostname from the client's (or rather: potential attacker's) request, and actually try to generate a *new* keypair and certificate using that filename, if it doesn't find an existing one. This behaviour doesn't only enable unauthenticated clients do perform a DOS attack against a CUPS server that is configured to require authentication, but it isn't even documented in the manpage. And as if this wasn't bad enough already, starting with version 2.2b2, CUPS actually tries to load certificates from /etc/letsencrypt/live/HOSTNAME/, where HOSTNAME is a string coming directly from the client/potential attacker. Again, this is not documented anywhere (except for a single line in CHANGES.txt without any details), and aside from that, it is just as broken as the behaviour that I described in the above paragraph.

- Due to this behaviour, the user has no control whatsoever which certificate(s) actually get used by the server (and even worse, he doesn't have a chance to know this because the manpage doesn't tell him anything about this).

- The user can only use subject alternative names by manually creating two symlinks for every single subject alternative name in his certificate. If not impossible, this makes it unnecessary complicated to use certificates containing a SAN (which is strongly encouraged by the Let's Encrypt project because they limit the number of certificates issued for a single DNS zone).

My proposal to fix these problems:

- Reverse commit 9e5e2ceff5ff91a95f2c62057f4bcb2efb97cbdf. Alternatively, at the very least, introduce a configuration directive to disable this behaviour, set the default so it is disabled by default, and document the whole mess properly.

- Don't generate certificates at all (or at the very least introduce a configuration directive to disable this insane behaviour, and set the default so this behaviour is disabled by default).

- Add a configuration directive to enable users to load single certificates and private keys by specifying a complete file path.

- Load *all* of the certificates (and their corresponding private keys) when cupsd is started, and just let GnuTLS figure out which one of them to use when a request comes in.

**Comment by michaelrsweet** [comment]
HTTP Upgrade to TLS specifies that we use the Host header, just as HTTPS uses SNI. Both are provided by the client and validated by the server prior to use. There is nothing inherently broken or insecure in this, although you could argue for adding a new directive to cupsd.conf (or cups-files.conf) to disable the automatic generation of self-signed certificates (a la SSH). The location of certificates is OS-specific, so we haven't been going into great detail about it in the documentation - we can look into ways of documenting this more clearly and use this bug to track it.

We are actively trying to limit the number of TLS configuration directives in CUPS, both because we need to support them on multiple OS's (and with multiple TLS libraries) and because it increases the amount of shit we need to test and support.

Subject Alternate Name support is poor today mainly because there is limited OS support and absolutely no common TLS certificate store on Linux. I'm happy to address a bug report specifically about improving SAN support.

Regarding your proposals:

1. We won't add a directive to disable support for Let's Encrypt. Realistically it is the only way most users will be able to provide a CA-signed certificate for their print services, and if you don't have Let's Encrypt installed and configured on your system then it doesn't get used.

2. We won't disable self-signed certificate generation by default. This would break printer sharing as we've been shipping it for 10+ years and subject users to OS-specific commands they didn't need to know before. Even SSH comes setup to do this out of the box (typically as part of the installation package).

3. Allowing users to specify certificates and private keys directly opens up security holes and is not possible on macOS and Windows (they require certs and keys to be stored in their own stuff).

4. GNU TLS isn't used everywhere and would need us to load all certs from a directory (or set of files) just like we are doing today. Plus we need to access the certs and keys from multiple processes. What we have implemented for systems using GNU TLS is definitely bare-bones, but until Linux provides a true secure data store for this we have no viable alternative.

**Comment by hardfalcon** [comment]
Generating *one* default keypair/certificate would be totally fine, but generating a new one for every single hostname doesn't make any sense. Since we are talking about self-signed certificates, these can't be verified by the client anyhow, and the current behaviour is just a plain and simple DOS vector, without providing any additional security whatsoever. In fact, current behaviour even decreases security, because the client can't just "TOFU" once for the whole CUPS server, but will have to accept a completely new keypair every time the IP address or hostname changes.

I totally understand your reservations about adding new configuration directives for the SSL/TLS setup, but unfortunately, thats a really shitty choice considering the broken defaults that CUPS is currently using (at least on Linux).

Regarding the proposals:

1. The code that you introduced to "support" Let's Encrypt creates more problems than it solves:
- Right now, it is undocumented behaviour.
- It will only work with one single ACME implementation (and even there, it will only work as long as you don't use more than one hostname per certificate).
- It breaks things in situations where you have certificates for another daemon (say a mailserver) in /etc/letsencrypt/live/ and you had a special certificates (for example for HTTPS on port 631) for your CUPS daemon in /etc/cups/ssl/. In this scenario, your old configuration breaks due to undocumented behaviour, and CUPS starts using SSL certificates that it isn't supposed to use.

2. I don't see why *not* generating a new certificate for every hostname in a request thrown at the server would break anything. It would be perfectly fine to generate *one* default certificate for situations where the certificate can't be verified anyhow by the client connecting to the CUPS server (OpenSSH also doesn't generate a new keypair for every IP address/network interface it is listening on). As the generated certificates are self-signed, they can't be validated by clients, and they don't offer any additional security in any reasonable threat model. Hell, you don't even use perfect forward secrecy cipher suites when RSA certificates are used (which is the default). The only way to make cupsd offer PFS cipher suites for SSL conections seems to be to manually setup certificates with ECDSA keys (at least on Linux, when using GnuTLS). Whilst it *is* possible to configure CUPS in a way that gives you an acceptable (albeit far from perfect) level of SSL/TLS security, both the defaults consistently give you the most insane and broken values possible for every single option (and the documentation in its current state is totally useless in helping users to fix this mess).

3. I'm sorry, but this argument doesn't make any sense to me. When launched/restarted, cupsd checks permissions for the directory containing the certificate keys and fixes them to chmod 700 (kudos for that btw!). Just do the same (chmod 600) for private key files, and document that behaviour in the manpage.

4. That shouldn't be a problem. The GnuTLS documentation for the gnutls_certificate_set_key() function specifically states "This function may be called more than once, in case multiple keys/certificates exist for the server".


In its current state, with its current defaults, the whole SSL support in cups is just a plain waste of CPU cycles unless the user/admin spends half a day on trying to find ways of sneaking around the above named problems and insanities. And even then, most of those problems remain unsolved.

**Comment by michaelrsweet** [comment]
"man client.conf": TLS policies are enforced based on the settings in client.conf. The default policy is TOFU, with the server only generating ONE certificate for the name used by the client (which is generally advertised by the server or configured by an administrator). The client doesn't use a different server name each time, so naturally the server doesn't create a new certificate each time.

As for the documentation side of things, we will use this bug to track documentation of Let's Encrypt support, among other things that you have identified as unexpected or undocumented.

As for using Let's Encrypt certs over local (self-signed) certificates, I can perhaps sympathize with preferring certs from /etc/cups/ssl over /etc/letsencrypt/live and will consider *that* change.

Certs are supposed to be associated with the hostnames they are used for - otherwise you are limited to TOFU (ssh behavior) without the option of a simple hostname validation to protect against some classes of man-in-the-middle attacks.

Regarding doing a chmod of the /etc/cups/ssl files, that is certainly a possibility although we normally do want the certificates to be world-readable so that an admin can force any client on the system to reject a cert that doesn't match.

We cannot support loading certs from arbitrary locations on macOS or Windows (not allowed for valid security reasons), and on platforms that use GNU TLS we only allow specific locations that we can trust.

Finally, we cannot use ECDSA certs by default because many clients (and printers!) do not support them. Obviously you can generate your own certs and CUPS will use them.

**Comment by michaelrsweet** [comment]
[master efed056] Add CreateSelfSignedCerts directive for cups-files.conf (Issue #4876)

**Comment by michaelrsweet** [comment]
[master 0ebe8e7] Document how encryption works (Issue #4876)

**Comment by michaelrsweet** [comment]
[master 7b98e44] Use self-signed certificates over CA-signed ones (Issue #4870)

**Comment by michaelrsweet** [comment]
OK, I believe we have made all of the changes needed to address this issue. This will be part of the 2.2.1 release.
