### ISSUE TITLE
Printerror with 'User' added to ~/.cups/client.conf

### ISSUE THREAD

**Issue by hille** [apple/cups#4878]
Hi, I'm having some trouble wile printing to a windows shared printer. 
The printer asks for authentication and this username is different from the login-name.
So I've added client.conf to ~/.cups and put 'User authname'. Looking in the cups documentation I've noticed that this setting will be deprecated as soon as Sierra rolls out, but I've got about 100 macs at work that for various reasons can't upgrade yet.

If the client.conf file isn't present, the document I try to print goes through the queue, but since its using the login-name as authname my print doesn't come out. When I add client.conf again and try to print I get an error-message that is very generic. "The print has failed"

This seems to be happening to different osx types and cups versions.

**Testmachines:**
```
Machine 1:
Cups: v2.0.0
Osx: 10.10.5
User is part of lpadmin group

Machine 2:
Cups v2.1.0
Osx: 10.11.5
User is part of lpadmin group

User$ lpstat -s
device for Printer: smb://work.server/Printer
```

**var/logs/cups error_log:**
`pam_authenticate() returned 9 (authentication error)`

**Console message:**
```
PrintUITool[413]: -[PMAuthPrintingTool printJobWithTicket:type:printFD:jobID:]: ipp_print_job failed: Unauthorized
TextEdit[467]: Printing failed because PMSessionEndDocumentNoDialog() returned 4096.
```

**Comment by michaelrsweet** [comment]
OK, you can't use the User directive for that - it sets the default local username for authentication, but since there is no local user with that name it will never succeed in queuing the job.

The two ways to do this are:

1. Put the username and password in the device URI, e.g. "smb://authname:password@work.server/Printer"

2. Print and enter the correct credentials when prompted. (some situations may require you run "lpadmin -p printer -o auth-info-required=username,password" to tell CUPS you need to enter credentials)

**Comment by michaelrsweet** [comment]
Oh, and if either of the above options do not work for you, please submit a bug through bugreport.apple.com since most of the software that is involved is not CUPS...

**Comment by hille** [comment]
Ok, thanks for the reply. I tried 1. earlier to no avail, but I'll give 2. a go.
And I will take it over to the apple forum if something comes up!
