### ISSUE TITLE
CUPS code style

### ISSUE THREAD

**Issue by dimV36** [apple/cups#4882]
Does CUPS code have any code style? If not, I suggest to reform code to one code style (e.g. use only spaces or tabs for indention). As for me (and contributors maybe) CUPS code is difficult to read and errors finding.

**Comment by michaelrsweet** [comment]
Please see:

    https://www.cups.org/doc/spec-cmp.html

TL;DR: Tabs at 8 columns, indent of 2 spaces, standard header on source files and functions.

(and generally speaking the only complaint we've had about usability has been due to tabs since some IDEs default to 4 column tabs... We've been considering converting to spaces to avoid that...)

**Comment by michaelrsweet** [comment]
(also CONTRIBUTING.md has the same content in the source tarball...)
