### ISSUE TITLE
Single Pages are printed on the wrong side of letter headed paper

### ISSUE THREAD

**Issue by nsanli** [apple/cups#4884]
If we print a single page on letter headed paper using Cups 1.7.5 on
Debian jessie, with some documents it comes out on the wrong (blank)
side of the paper.

We have tracked it down to code in pstops.c, which is still in git master:
https://raw.githubusercontent.com/apple/cups/master/filter/pstops.c

The code for cupsEvenDuplex is ignored if the value after "%%Pages:" is
less than or equal to 1 (or the number of pages per sheet, if nup > 1):

  if (Duplex &&
       (doc->slow_collate || doc->slow_order ||
        ((attr = ppdFindAttr(ppd, "cupsEvenDuplex", NULL)) != NULL &&
         attr->value && !_cups_strcasecmp(attr->value, "true"))))
    doc->slow_duplex = 1;
  else
    doc->slow_duplex = 0;

...

    if (!strncmp(line, "%%Pages:", 8))
    {
...
      if (Duplex && (pages = atoi(line + 8)) > 0 && pages <= doc->number_up)
      {
       /*
        * Since we will only be printing on a single page, disable duplexing.
        */

        Duplex           = 0;
        doc->slow_duplex = 0;

...

  if (doc->slow_duplex && (doc->page & 1))
  {
   /*
    * Make sure we have an even number of pages...
    */

PostScript files generated by Latex-dvips have "%%Pages: 1" in the header.
PostScript files generated by enscript have "%%Pages: (atend)" in the header.

For documents having "%%Pages: (atend)" it works correctly.

Our workaround is a wrapper script to replace "%%Pages: 1" with "%%Pages:
(atend)", so "*cupsEvenDuplex: True" always gets used. See:
https://hg.intevation.de/adminton/file/default/shebang/pstops-wrapper

But it would ge better if Cups would keep "doc->slow_duplex = 1", even
for single-page documents, because we think that this is the intended
effect of "*cupsEvenDuplex: True", as correctly done with documents
having 3/5/7/... pages.

**Comment by michaelrsweet** [comment]
No. Duplex is disabled for single page jobs ON PURPOSE. This isn't something we are going to change, sorry.

**Comment by ThomasAH** [comment]
Can you tell us what the purpose is? (compared to the last page of documents with 3/5/7/9 pages)
Or what is your suggested work flow for a printer which contains letterhead paper?

**Comment by michaelrsweet** [comment]
Put the letterhead in the printer as indicated by the pictures in the paper tray.

The purpose of cupsEvenDuplex is to work around known printer firmware bugs where the printer would crash (hard) if you sent it a duplex job with an odd number of pages. The purpose of disabling duplex for 1-page jobs is to avoid other known firmware bugs, plus yield faster printing for the most common use case.

**Comment by ThomasAH** [comment]
We have a second printer with letterhead paper and forced simplex mode if we need faster prints.

But for this printer, if we turn the paper, it will be printed on the wrong side for documents with 2/3/4/... pages **and** with documents having `(atend)` instead of the number of pages in the header. So not really an option.

If this is mostly a workaround for a firmware bug in certain firmware, there needs to be a way to disable it, that doesn't require changing the source code (which we did many years and which delays applying security updates), or using our wrapper as a workaround (which we do now to be able to easily install security updates).

What do you suggest?

**Comment by michaelrsweet** [comment]
What I suggest is that your driver is the cause of the problems. If duplex printing changes the side of the sheet that is imaged first ("front side"), that is a bug in the driver.

We can't work around issues like that in pstops or any other software in CUPS.

**Comment by swilde** [comment]
Could you please elaborate on the bug in our driver you are suggesting is the cause of the problem?  To me it looks like that the driver behaves the same (creates equivalent data) for documents with one and documents with more than one page.  Why is it a bug in the driver to expect the first page of the document to get printed on the same site of the paper in all cases?

**Comment by michaelrsweet** [comment]
The bug is having different printing behaviour (what side gets printed on first) between a simplex and a duplex job.

**Comment by ThomasAH** [comment]
Isn't this a very usual behaviour for printers, because otherwise you would have to turn every page around to have them in the correct order? Page 1 on top of the first sheet, page 2 on the back side, page 3 on top of the second sheet, and so on.
So not a bug, but a feature.

And I thought the cupsEvenDuplex setting is exactly to work with printers which have this in many situations useful behaviour.

**Comment by nsanli** [comment]
Hello Mr Sweet,

I would like to point you, again, to this issue, because this Problem isn't solved.
