### ISSUE TITLE
IPP Everywhere: Discovery issues/optimizations

### ISSUE THREAD

**Issue by stephanwib** [apple/cups#4909]
I have found some issues concerning CUPS discovery of HP and Lexmark printers.

1) Lexmark printer does not provide "media-size-supported". A fallback based on "media-supported" should be implemented in CUPS.

2) The color modes of Lexmark printer can not be retrieved. The printer does not offer "print-color-mode-supported". It does, however, offer "output-mode-supported". This should be honored in _ppdCreateFromIPP().

3) The media type discovery code looks for "media-type" and "media-type-supported" encoded as IPP_TAG_KEYWORD. However, the HP printer sends these values encoded as IPP_TAG_NAME.

4) The printer resolutions cannot be recognized based on "printer-resolution-supported".

**Comment by michaelrsweet** [comment]
FWIW, 'name' values are deprecated in IPP and may cause problems. Can you run the following command against your HP printer and attach the output:

    ipptool -tv ipp://... get-printer-attributes.test

where 'ipp://...' is the device URI you are using for the printer?

Thanks!

**Comment by michaelrsweet** [comment]
[master 670172e] Improve IPP Everywhere support (Issue #4909)

Pushed some changes for this issue. If those don't help, please post the output of the ipptool command above (plus the PPD file) for any of the affected printers, thanks!

**Comment by stephanwib** [comment]
Attached the output of ipptool and the PPDs resulting from the current snapshot.

[hp-getattr.txt](https://github.com/apple/cups/files/558001/hp-getattr.txt)
[hp-e.ppd.txt](https://github.com/apple/cups/files/558006/hp-e.ppd.txt)
[lex-e.ppd.txt](https://github.com/apple/cups/files/558007/lex-e.ppd.txt)
[lex-getattr.txt](https://github.com/apple/cups/files/558002/lex-getattr.txt)

**Comment by michaelrsweet** [comment]
How do things work with the changes?

**Comment by stephanwib** [comment]
The PPDs look pretty good. I can provide more feedback next week after some
testing.

Thanks for comitting these fixes!

2016-10-28 14:03 GMT+02:00 Michael R Sweet <notifications@github.com>:

**Comment by michaelrsweet** [comment]
[master 23862bc] More changes for Issue #4909:

**Comment by stephanwib** [comment]
I think point 1 - 3 are fixed!

**Comment by michaelrsweet** [comment]
Good! As for the last item, the PPD will not have a Resolution option in it, but instead we set the resolution based on print quality and use the DefaultResolution keyword to tell applications what resolution to use for any flattened/bitmap artwork in the print job. That should be working as well, but if not please let me know!

**Comment by stephanwib** [comment]
Well, concerning the resolutions, both printers show 600dpi and 1200dpi in printer-resolution-supported, which also matches what the vendor drivers say.

The discovery of the Lexmark printer leaves very different options in the PPD:

*cupsPrintQuality Draft/Draft: "<</HWResolution[300 150]>>setpagedevice"
*cupsPrintQuality Normal/Normal: "<</HWResolution[300 300]>>setpagedevice"
*cupsPrintQuality High/High: "<</HWResolution[600 600]>>setpagedevice"

The values for the HP printer differ, too:

*cupsPrintQuality Draft/Draft: "<</HWResolution[600 300]>>setpagedevice"
*cupsPrintQuality Normal/Normal: "<</HWResolution[600 600]>>setpagedevice"

Gathering values from printer-resolution-supported would lead to the right options, I think.

**Comment by michaelrsweet** [comment]
The printer-resolution[-supported/-default] refers to the physical output resolutions and not the supported input (document) resolutions, which often differ. The reason is that the printer has to do color and dithering/halftoning on the incoming document data to produce the output data for the print head/drum.

So while we might fallback on printer-resolution-supported for the DefaultResolution keyword in the PPD (so that any rendered imagery in the document uses a "compatible" resolution that can be scaled by integer factors to avoid aliasing effects), we will not use it to determine the resolution that we ask the RIP filters (cgpdftoraster, pstoraster, pdftoraster, etc.) to produce since none of these printers accept raster data at their full resolution. Instead we look at the pwg-raster-document-resolution-supported (PWG Raster) and urf-supported (AirPrint) attributes which supply the supported raster resolutions.

In the case of these two printers, they specify 600dpi (HP) and 300dpi+600dpi (Lexmark) as supported raster resolutions, so we use those to map print quality to a corresponding resolution (and similarly the printer will map the IPP print-quality value to an output resolution...)
