### ISSUE TITLE
Move file filter/raster.c into libcupsimage

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4917]
I have looked through the changes on the rastertopwg filter to see how it adds support for Apple's URF Raster format. There I have seen that the generation and consumption of URF files is implemented in the filter/raster.c file and not in a file in the cups/ directory (the source of CUPS' libraries). Why is this done this way? Can this functionality be moved into libcupsimage, to reduce duplicate code and to simplify support for the URF format?

**Comment by tillkamppeter** [comment]
Sorry, I am seeing now that libcupsimage is built in the filter/ directory not in the cups/ directory (should perhaps an image/ directory be introduced to separate libcupsimage from the filter executables?).

**Comment by michaelrsweet** [comment]
Till,

The libcupsimage library has always been built in the filter directory, which used to contain a lot more code for all of the image file formats and so forth (that is now part of cups-filters).

*If* I moved things I'd probably put what's left of libcupsimage into the "cups" directory (since that's where the header files live). But right now that is really low priority for me... :)
