### ISSUE TITLE
 ￼Edit New issue CUPS queues emulate IPP Everywhere printers: Number of color modes in capabilities reported by IPP very restricted

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4951]
If I treat a CUPS queue as an IPP Everywhere printer (to allow print dialogs to work without PPD API, see also Issue #4950) in the queue reports the possible color modes via this code (in scheduler/printers.c):

`
   /*
    * print-color-mode...
    */

    if (ppd->color_device)
    {
      static const char * const color_modes[] =
      {
        "monochrome",
	"color"
      };

      ippAddStrings(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD,
                    "print-color-mode-supported", 2, NULL, color_modes);
      ippAddString(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD,
                   "print-color-mode-default", NULL, "color");
      ippAddStrings(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD, "pwg-raster-document-type-supported", 3, NULL, pwg_raster_document_types);
    }
    else
    {
      ippAddString(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD,
                   "print-color-mode-supported", NULL, "monochrome");
      ippAddString(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD,
                   "print-color-mode-default", NULL, "monochrome");
      ippAddStrings(p->ppd_attrs, IPP_TAG_PRINTER, IPP_TAG_KEYWORD, "pwg-raster-document-type-supported", 2, NULL, pwg_raster_document_types);
    }
`

This means that the color modes informed via IPP depend only on the color printer bit in the PPD file, not on a "ColorModel" option which the PPD file could contain.
This leads to some possible color modes do not get known to a client or for example if the printer is capable of printing with 16 bits per color (48/64 bits per pixel), high-color depth pictures (for example developed from raw pictures from a camera) cannot be printed in their original color depth.
If a print dialog would not use PPD APIs to get the options from the PPD but IPP polling instead, it would not get the full capabilities of the printer.

**Comment by michaelrsweet** [comment]
print-color-mode is limited to the basic intent. Different color space support is a feature of the document format - so for PWG raster it would be the pwg-raster-document-types-supported values, and for PDF it is just the ICC profile assigned to the colors/images used.

We already support this when creating a PPD, and it is possible I could add detection of the "AdobeRGB" ColorModel choice in cupsd, but in reality it doesn't matter since a client will never be sending raster data (PDF is supported by CUPS and preferred over PWG raster).
