### ISSUE TITLE
Tray selection for printing PDF

### ISSUE THREAD

**Issue by guettli** [apple/cups#4964]
According to this [post](https://forums.adobe.com/thread/1264601) you need [JDF (Job Definition Format)](https://en.wikipedia.org/wiki/Job_Definition_Format) to support tray selection.

Does cups support JDF?

If not, how to specify trays for printing PDF?

**Comment by stephanwib** [comment]
There are other options for printer control (not just trays) when printing document formats that don´t support job control or print tickets.

The best is to use IPP (see CUPS IPP Everywhere support). If a printer doesn´t support that, you probably can control it using PJL commands. I don´t know vendors who offer PPDs that produce PDF+PJL, but you might have a look at some experimental ones from the cups-filters project here:

https://github.com/Distrotech/cups-filters/tree/distrotech-cups-filters/ppd

**Comment by michaelrsweet** [comment]
@guettli JDF is typically used in production printing environments (think: books, magazines, product packaging, etc.) and not in office/home printing environments.

As @stephanwib points out, CUPS uses IPP which provides a full range of support for things like media and tray selection, finishing (stapling/folding/etc.), and so forth. Examples can be found in the CUPS online help, "man lp", and on the CUPS web site at "https://www.cups.org/doc/options.html".

(there are a lot of different ways that printer features are supported; CUPS tries to support them all using the standard IPP attributes and values so that you are insulated from these differences)

**Comment by guettli** [comment]
Thank you for sharing your valuable knowledge.
