### ISSUE TITLE
Jobs page UI usability issues

### ISSUE THREAD

**Issue by kylemacfarlane** [apple/cups#4978]
Here's some issues I've noticed since the jobs page was redone (and some existed before as well).

1. The total number of jobs seems to be off by one, i.e. if MaxJobs is set to 500 then the jobs page will say "Showing 100 of 499".
2. The pagination doesn't update with the page, i.e. pages 1, 2, 3, 4 will all say "Showing 100 of 499" instead of "1-100", "101-200", etc so you have to look at the URL to find out what page you're actually on.
3. There's no indication of how the job list is ordered which is a problem since different types of lists are ordered differently.

**Comment by michaelrsweet** [comment]
I hesitate to have the web interface say "showing 1-100" since the job IDs may not be contiguous. Maybe look at the first and last job ID on the current page instead...  Or show page numbers and not "jobs N to M"?

The ordering can be displayed on the page, although pending/active job order will be a little more challenging to describe ("Jobs in print order; held jobs may appear at the top of the list"?)

**Comment by michaelrsweet** [comment]
[master 1f3f503a2] Updated the job listing in the web interface (Issue #4978)

I opted to simply remove the display of the job ID and state the order the jobs are shown instead.
