### ISSUE TITLE
Driverless printing can only be set up with the lpadmin command line tool

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4984]
Not considering cups-browsed and the driverless utility of cups-filters, with CUPS itself a driverless printer setup is only possible with the lpadmin command line utility, supplying the "-m everywhere" command line option (with a device URI for connection via IPP).
There is no way to do the same thing by sending IPP requests doing to create a print queue (out of a C program, using CUPS' IPP API) or using the CUPS web interface.
As in the web interface you can select a raw queue there should be also some option to select a driverless queue (grayed out when connection is not IPP or causing an error then).
The IPP calls for creating a print queue need to have some possibility to trigger CUPS' internal PPD generator to generate the PPD based on IPP-polling the printer.
If this is possible but I did not find out how. Please add the needed bits to the documentation.

**Comment by michaelrsweet** [comment]
The modern printing APIs automatically create a "driverless" local queue as needed using the CUPS-Create-Local-Printer operation.  These APIs have been documented since CUPS 1.4. Please use them.

**Comment by tillkamppeter** [comment]
I have tried it now. I did

wget -O cups-create-local-printer.test 'https://raw.githubusercontent.com/apple/cups/master/test/cups-create-local-printer.test'

then

ippfind ! --txt printer-type --and \( --txt-pdl image/pwg-raster --or --txt-pdl image/urf \)

or simply

driverless

and then for each resulting URI

ipptool -tv -d name=<NAME> -d device=<URI> ./cups-create-local-printer.test

to set up all driverless-capable printers.

Is this the intended way to proceed after each start of cupsd? For example in start-up script for cupsd? Or is this procedure intended to be done when opening a print dialog?

**Comment by michaelrsweet** [comment]
Till,

The intent is that you only add a queue when you need to print something. Otherwise why bother using up memory, CPU cycles, etc. for printers that are only ever created "just in case" the user wants to print?

**Comment by imsedgar** [comment]
It is important for an administrator to create printer queues on managed linux computers "just in case" the user wants to print, because normal user cannot create printers and set the (default) options, and they should not be able to do so. Normal users do not know what printers are available and how to address them. Usually printers are in other subnets (for security reasons). At least at a "printer server" there must be created the printers by the administrator, and print clients may get there printer list by cups-browsed, for example. Think of network printers in a central printing room, used by many staff and students, not of a printer for personal use.

**Comment by michaelrsweet** [comment]
@imsedgar Nothing prevents you from creating queues - they still exist and are supported. But in the (far more common) case where the user connects to a local Wi-Fi segment and then prints to a local printer accessible from the local network segment, CUPS can create a temporary queue (and yes, even ordinary users can do this - the operation was designed explicitly for that purpose) to send a print job to that local printer or print server, after which the queue goes away.

The modern print APIs show both "permanent" print queues and locally available printers. When a printer is chosen that doesn't have a permanent queue setup, CUPS will create a temporary queue for the user so that the job can be printed.

**Comment by imsedgar** [comment]
@michaelrsweet Thanks for clarification!
