### ISSUE TITLE
Shared parameter

### ISSUE THREAD

**Issue by jimiebolha** [apple/cups#5001]
When you send a print to a queue configured by the smb connection, the Shared Yes parameter is automatically changed to No. No longer being able to send impressions.

CUPS version 1.7.5.
Debian 8.8
smbclient: 2:4.2.14

**Comment by michaelrsweet** [comment]
You cannot share a SMB print queue because proxying of Kerberos (ActiveDirectory) credentials is not feasible in most cases. (and in the few cases where it can be made to work, you do it by granting the CUPS server privileges that can threaten the security of the whole network...)

So sorry, but this is working as designed... :/

**Comment by jimiebolha** [comment]
Thank you.
