### ISSUE TITLE
printing blank pages

### ISSUE THREAD

**Issue by john-walsh** [apple/cups#5002]
On a HP Color LaserJet Pro M452nw printer.

Linux OS, CUPS 2.2.3-1.

IP connection.

I think the problem is more to do with memory in the printer - filling up, or some usage of it. The problem goes away (for a couple of prints) after a power cycle of the printer. I have not tried a factory reset yet.

And the problem shows on 3 systems, so I don't think all 3 systems got the same problem at the same time, when no updates had been applied o them.

The problem:

Printer and CUPS had been working fine for months...

Then, printing directly to the printer from LibreOffice/qpdfview, the pages are produced, but they are blank. At least of text, images are printed. GIMP also prints fine.

BUT, printing to file (PDF) and then sending the pdf file to the printer (lp -o raw file.pdf) works - the text is printed fine.

If someone wants to suggest any tests, I'm happy to help run them.

**Comment by jsmeix** [comment]
We (at SUSE) got a customer issue report that was similar.
That report was about a
"HP LaserJet Enterprise 700 Color MFP m775" as listed at
http://hplipopensource.com/hplip-web/models/color_laserjet/hp_laserjet_700_color_mfp_m775.html
which reads (excerpts):
<pre>
Other Information:
...
APDK device class(es): Postscript
HPLIP device sub-class(es): Normal
</pre>
which indicates it is a regular PostScript printer
same as yours at
http://hplipopensource.com/hplip-web/models/color_laserjet/hp_color_laserjet_m452nw.html
which also shows
<pre>
APDK device class(es): Postscript	
HPLIP device sub-class(es): Normal
</pre>
Accordingly I assume it is set up as regular PostScript printer
which means the printer device gets PostScript data as input
via the usual conversion steps in the printing system
(nowadays implemented mainly via "cups-filters"),
cf. https://en.opensuse.org/Concepts_printing

In contrast when you do "lp -o raw file.pdf" you send PDF
directly to the printer.

Sometimes some PostScript printers do not like
certain kind of PostScript data.

In such cases it helps to activate in the printer device
that it prints out a PostScript error message when it fails
to process certain kind of PostScript input data.
Usually a PostScript printer's PostScript error message
does not help one to understand what actaully goes wrong
inside the printer but it shows that it fails inside the printer
and not on the computer that produces the PostScript data.

Nevertheless even when it fails inside the printer the actual
root cause can be faulty produced PostScript data.

In that particular case the solution was to
update the HP firmware on the
"HP LaserJet Enterprise 700 Color MFP m775".
Now that printer is working as expected.

If in your case updating the HP firmware does not help
you may have a look at
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
regarding how to diagnose the cause of your printing issue
and some basic tests that could help to find the root cause.

**Comment by john-walsh** [comment]
jsmeix - thanks for the thoughts.

As it happens, I was a developer on a PS RIP, just not the language side, but I know PS well.

My printer does 'auto upgrades' (I have to confirm it), so I assume the firmware is up to date. It has done an update in the past.

Yes, the driver is set to use PS:

```
$ egrep 'NickName|cupsFilter' /etc/cups/ppd/HP_Color_LaserJet_M452nw.ppd
*ShortNickName: "HP Color LaserJet Pro M452"
*NickName: "HP Color LaserJet Pro M452 Postscript (recommended)"
*cupsFilter: "application/vnd.cups-postscript 0 hpps"

```

I decided to try adding a new printer in CUPS, and making it use the PDF driver.

Starting with my printer, and changing the details as you go through the install (name HP -> PDF), I eneded up with:

```
Name: PDF_Color_LaserJet_M452nw
Make: Generic
Model: Generic PDF Printer (en)

```
And it works - sending PDF to the printer gets around the problem in the PS code (whatever it is/was).

NB. I still have the HP/PS printer installed, so I can choose which I use. And I assume doing a 'factory reset' on the printer will clear any memory buildup problem, so it would work fine again for a few months... until the problem came back.

But I'll use the PDF option as my default. Any problems and I can try the PS driver...

So my new PDF printer is:

```
$ egrep 'NickName|cupsFilter' /etc/cups/ppd/PDF_Color_LaserJet_M452nw.ppd
*ShortNickName: "Generic PDF Printer"
*NickName:      "Generic PDF Printer"
*cupsFilter: "application/vnd.cups-pdf 0 -"
*cupsFilter2: "application/pdf application/vnd.cups-pdf 0 pdftopdf"

```

**Comment by john-walsh** [comment]
I have an idea.

To anyone that's good at PostScript :- 

My suspicion is that the printer is having some form of memory problem - it filling up, cached fonts, ... leading to a problem in accepting new jobs and not being able to process fonts.

Could someone write a scrip (PS file) to send to the printer, to print out the memory status, then clear any caches and print out the new memory status (on one page)?

Maybe have options set at the start of the file:

`/clear_font_cache true def
`
I'm curious if a PS file can solve the problem, rather than having to turn it off and on again, or doing a factory reset every day...

Thanks.

**Comment by jsmeix** [comment]
My PostScript knowledge is insufficient to answer it
but perhaps you could ask the Ghostscript experts
at stackoverflow via a "ghostscript" tagged question, cf.
http://stackoverflow.com/questions/tagged/ghostscript

**Comment by michaelrsweet** [comment]
This particular printer should work with the IPP Everywhere driver...

**Comment by john-walsh** [comment]
From memory (of when IPP was first poposed), IPP does not define/specify the 'print language' to use, but just the finding and connecting to the printer, and interaction negociation...

So would/might the IPP driver then use the PS driver for the print job?

With this printer, IPP could choose PS, PDF, PCL...

**Comment by michaelrsweet** [comment]
IPP (the core protocol) does not mandate a particular PDL, but IPP Everywhere is a special profile of IPP that requires support for PWG Raster and JPEG (PDF is optional), and has a certification program. IPP Everywhere allows clients to discover and print to these printers using a generic driver.

Most printers sold since 2010 support what is needed for the IPP Everywhere driver in CUPS...

**Comment by john-walsh** [comment]
That's good to know, thanks.

I do just like PS and PDF, as I was a RIP developer for 10 years. But if I need, IPPE will do.
