### ISSUE TITLE
On shutdown, cupsd does not remove the PPDs of temporary print queues

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5003]
CUPS 2.2.x has the capability of auto-creating print queues for IPP printers which support driverless printing. One simply accesses printers listed by cupsEnumDests() and CUPS creates a queue automatically.
These queues are supposed to get removed on shutdown of cupsd, but what I observe after shutting down cupsd the queue's (auto-generated) PPD file stays in /etc/cups/ppd/. It should be removed, as the queue is removed.

**Comment by michaelrsweet** [comment]
Well, the code is certainly setup (in cupsdDeletePrinter) to delete the temporary PPD. Investigating...

**Comment by michaelrsweet** [comment]
OK, we're never calling cupsdDeleteAllPrinters on shutdown, which is why the code isn't getting run...

I've added a new cupsdDeleteTemporaryPrinters function that gets called periodically while cupsd is running and on exit - this will make queues temporary even when printer sharing or the web interface are enabled.

[master b49741428] Delete temporary printers periodically and on shutdown (Issue #5003)
