### ISSUE TITLE
Temporary queues still do not go away

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5009]
After having solved Issue #5003 and Issue #5008 the temporary queue does still not go away for me.
Did you set the "printer->temporary = 1;"? I do not see such thing in your code.
By the way, would be nice to note the temporary state also in printers.conf, so that if CUPS gets hard-killed ("kill -9") that in the next session the remaining queue is considered temporary.

**Comment by michaelrsweet** [comment]
(Till, you can comment on closed issues in Github and I can re-open them as needed, particularly when I haven't done a new release yet...)

I've checked and for some reason I wasn't setting the temporary flag in create_local_printer. That is now fixed:

[master 167e0655b] Make sure printer-is-temporary flag is set when creating a local queue (Issue #5009)

Regarding printers.conf, temporary queues are explicitly omitted from printers.conf because they (and their jobs) are not supposed to survive restarts.

**Comment by tillkamppeter** [comment]
Thank you very much. I have tried now and on shutdown the queue actually goes away. Only when I leave CUPS running the queue does not go away (I had it running for around 15 minutes).

**Comment by michaelrsweet** [comment]
Till, the printer deletion while cupsd was running was tied to the job history updates, which could be longer than 15 minutes.  I've separated that now so that we get rid of those queues more aggressively:

[master e1bb4a6e9] Make local printer deletion independent of job history updates.

**Comment by tillkamppeter** [comment]
OK, thanks.

**Comment by tillkamppeter** [comment]
I tested it and it is working correctly now.
