### ISSUE TITLE
How to make automatic printer selection name different from display name?

### ISSUE THREAD

**Issue by severach** [apple/cups#5021]
When adding a new printer CUPS often automatically selects the right driver. I've figured out that CUPS is matching on `*Manufacturer` and the text in '()' to `*NickName`. Unfortunately by putting the right text in `*NickName` for auto select, the text that shows and sorts in the printer model list also changes.

I see that the `*NickName` match is a "starts with" match so I can put any text I want after the match string. That isn't enough. How can I make the text in the printer model list completely different than the text used for auto select?

Is there any way to have more than one match string so multiple models can auto select to a single ppd?

Is printer auto selection documented anywhere?

**Comment by michaelrsweet** [comment]
PostScript driver matching uses Product, which can be repeated to support multiple models.

Non-PostScript driver matching used 1284DeviceId and NickName, which cannot be repeated - you need a separate PPD (or drv file, or compressed tar archive of PPDs) for each model of non-PostScript printer.

As for documentation, there are so many hacks, cludges, and workarounds in place (both in CUPS plus all of the other OS-supplied driver picking code) that documentation is impossible. We try to match the make and model, 1284 device ID, and PostScript product strings against the corresponding fields in the PPD. The matching sometimes works.

All that said, drivers are a legacy feature of CUPS and we are not working on making them better. Almost all printers sold since 2010 support IPP enough for CUPS to use them with the "IPP Everywhere" driver, which is the recommended path going forward.

**Comment by severach** [comment]
Easily solved. It's not a starts with match, it's a contains match. That allows me to start the text with how I want it sorted and put the match string in the middle where nobody is looking.

I use LPR or JetDirect with IP addresses. Everything else is way too much trouble to get working and too hard to maintain because the URLs are unintelligible. 

* IPP/driverless requires way too many widgets (mdns,avahi) to operate properly. IPP query errors are unhelpful.
* The driverless driver won't show up with a typed url, only the autodetected one.
* **Discovered Network Printers** is not sorted. This isn't a problem with only a couple of printers but I have 42 printers with many duplicates and it's a huge problem.
* **Discovered Network Printers** does not display the connection type. Picking the right printer out of 42 is a maze of twisty little passages, all alike.
