### ISSUE TITLE
Update label printer drivers to use threshold dithering

### ISSUE THREAD

**Issue by gqbgqb** [apple/cups#5092]
We currently have an issue printing PDF (with or without scaling) where the output is fuzzy/not good of quality (refer to attached files). We don't have this issue in Ubuntu (CUPS 1.7.2/ver 14.04/64-bit and CUPS 2.2.2/ver 17.04/32-bit) using the same PDF, printer and drivers. 

I also couldn't find anything in the logs which might relate to this. I hope someone could advice me where to look. I can't figure if its Apple or CUPS issue. 

Environment/Setup: Mac OS X Sierra/CUPS 2.2.1/SATO CUPS driver/SATO WS408 printer

![barcode](https://user-images.githubusercontent.com/29476125/29606675-8d59a338-8821-11e7-9059-51b0cb16194a.png)

Thanks in advance.

**Comment by mwibeck** [comment]
Hi.
I have some additional information. I work at the same company as gqbgqb and have also been investigating the issue.
The issue is that gcpdftoraster (and pdftoraster) adds noise to the image parts of the pdf that is very visible on a low resolution monochrome device, such as a label printer.

Attached are files showing the issue
- testprint.pdf, original PDF.
- rasterview_ppd.txt, ppd to be used with maketestfiles.sh from the test-directory of https://github.com/michaelrsweet/rasterview
- cgpdftoraster-K-1-Banded.ras, result of rendering the testprint.pdf via cgpdftoraster
- pdftoraster-K-1-Banded.ras, result of rendering the testprint.pdf via pdftoraster
- gstoraster-K-1-Banded.ras, result of rendering the testprint.pdf via gstoraster

*.ras files can be viewed with Rasterview (http://michaelrsweet.github.io/rasterview/)

If this is a cups-filters, CUPS, or Apple macOS issue I am not sure.
I find it a bit confusing to find out where different filters come from.

If anyone could figure out a workaround on macOS, that would be great..

Regards,
/Magnus Wibeck

[testprint.pdf](https://github.com/apple/cups/files/1248943/testprint.pdf)
[result.zip](https://github.com/apple/cups/files/1248946/result.zip)
[rasterview_ppd.txt](https://github.com/apple/cups/files/1248948/rasterview_ppd.txt)

**Comment by michaelrsweet** [comment]
OK, so there are two issues:

1. The driver is relying on the RIP to produce a B&W image, but asking for 1-bit K data produces dithered data.  The driver should ask for 8-bit and use its own thresholding/dithering algorithm for consistent results.

2. The embedded barcode image has interpolation enabled (or is grayscale with blurry edges), which tells cgpdftoraster (and more specifically CoreGraphics) that the image needs to effectively be blurred instead of kept B&W. Ghostscript also honors the interpolation hint in the PDF file.

So the fix here is to fix the PDF file and/or the driver.

**Comment by donileo** [comment]
I am also having this issue with a thermal printer on OS X High Sierra 10.13.4. Its great that you guys have identified the issue but what fix can we all implement to fix this problem?

**Comment by michaelrsweet** [comment]
@donileo If the source barcode is embedded as a bitmap or uses a font, the fuzziness issues will not be present.

**Comment by donileo** [comment]
@michaelrsweet Unfortunately I am not controlling the original output of the pdf's that I am trying to print. They are being generated in this example from a shipping courier service called Shippingeasy.com. But this same problem exists for shipping label pdfs generated by ebay, amazon essentially all the major selling platforms.  They definitely are not using a font for the pdf and look to be images (though I can't tell if bitmap or JPEG or what format). When I open my pdfs and zoom to around 800-1000x the text definitely looks blurry so the entire pdf is an image not just the bar code section.
I am wondering if turning off interpolation on the pdf via some CLI or some property of the file itself may resolve the issue.

**Comment by donileo** [comment]
Hmm since I am unsure whether the issue is the interpolation here is my sample pdf. I think my issue still applies to this topic, if not I'll move it to another issue.

[sample-shipping.pdf](https://github.com/apple/cups/files/1873033/sample-shipping.pdf)

**Comment by donileo** [comment]
I think this issue is also very pertinent: #4820

**Comment by michaelrsweet** [comment]
Ghostscript is the producer of this PDF, and they didn't set the proper rendering options so the barcode images are both interpolated and JPEG'd. Garbage-in, garbage-out... :/

Not sure what we can possibly do to improve things here...

**Comment by mwibeck** [comment]
What we ended up doing at SATO, since we cannot control user input, is that we added an 8-bit option to our drivers and let the filter have a threshold option, so that the image ends up 1-bit, but without dithering, just a simple threshold cutoff.
That will work for most labels with barcodes and text.

**Comment by donileo** [comment]
@mwibeck Can you post how this would be done exactly? Not sure exactly how to do what you are saying.

**Comment by mwibeck** [comment]
Unless you can rewrite the filter it is not possible afaik.
We added 8 bit grayscale as an option in the ppd, and then the filter looks at the options passed. If it is 8 bit, we generate a b&w image based on a threshold.

You're most welcome buying SATO printers instead... :-)

**Comment by donileo** [comment]
@michaelrsweet Sounds great! Considering I can't just upgrade CUPS on OS X due to SIP I'm assuming I can just replace the rastertolabel filter and my Zebra ppd file and hopefully implement your changes?

Will these changes someday make it to OS X when Apple upgrades to the 2.3.x release?

**Comment by donileo** [comment]
@mwibeck Is there a way to communicate with you outside the scope of this issue? I acquired a SATO printer but its just refusing to print anything but its own self calibrated output.

**Comment by irfkhan** [comment]
I m not trying to piggyback on existing thread ,but also want to determine if this issue is related to what we are facing. 

Attached PDF printed from old cups and new cups, notice the decimal point, its almost invisible.

I went through individual printers and when it goes through gstoraster is where things become so light and dithering comes in.

[Scan_Doc0013.pdf](https://github.com/apple/cups/files/2290633/Scan_Doc0013.pdf)
[Scan_Doc0012.pdf](https://github.com/apple/cups/files/2290634/Scan_Doc0012.pdf)
[CCOAPRD Conc Req 799649710-Document-1.pdf](https://github.com/apple/cups/files/2290635/CCOAPRD.Conc.Req.799649710-Document-1.pdf)

Unfortunately for end users the visibility of the quantity without decimal can be chaotic

I have also attached rasterized file

it was done using the command below

/usr/sbin/cupsfilter -p  /etc/cups/ppd/NICK-T420-TEST-ZPL.ppd  -m application/vnd.cups-raster  /dbstage/dba/tmp2/799649710.pdf > irf.ras 2>log

**Comment by irfkhan** [comment]
Notable part is quantity , there is a decimal in one scan and not in other

its definitely after raster filter

**Comment by michaelrsweet** [comment]
OK, after much deliberation we have decided not to address this in CUPS. A subsequent revision of the ippserver sample code will include compatible "drivers" that offer this functionality to demonstrate the whole "printer application" approach.

**Comment by turntable** [comment]
I have this same issue with the barcode clarity as mentioned in this thread. I'm using a Zebra printer and the Zebra ZPL driver on macOS 10.14.6, CUPS 2.2.9. Since a fix was not included in 2.3 CUPS is there a further explanation on how I can resolve?

**Comment by dreamcat4** [comment]
Here on ubuntu 19.10 linux. Got a brand new thermal printer. And it's all the exact same issue in regards to the dithering being all wrong. This specific device happens to be an `xprinter xp-460b`. Which I found that it will print using the driver downloaded from TSC website. However the image is all screwed up.

The cups driver name is called `TSC TDP-247 (grayscale)`. With CUPS version `2.2.12`.

Sorry I don't fully understand the path to fixing this here so maybe some of you people can elaborate about the filter. And why this cannot be fixed in a single central place for all of the printers.

Does this mean that I need to contact TCL company and inform them there is an error in their driver? Because I definitely didn't buy my printer from those guys. Despite it being the same OEM device underneath. These guys were the other rebrand / reseller the company known as xprinter, only offers a windows driver package and nothing for the linux support.

Perhaps... can I work on adding this myself ?

Well here is the TSC linux drivers package downloads page https://www.tscprinters.com/EN/support/Support_Download/TDP-244#

It seems to just contain an archive with some PPD files. I cannot actually find where the driver part or it's source code actually is located for adding this `filter` as you are describing it. Unless it's a part of the precompiled `tscusb` executable file under that `backend/` subfolder? Perhaps that is a closed source part of these TSC company's drivers package?

Anyhow here is the PPD file https://gist.github.com/dreamcat4/8a74f6b5151a321fcac076c68dd6aed7

It doesn't mention anything about dithering. And there is no such 'dithering' setting in the printer options once installed.

**Comment by ddavidebor** [comment]
Hello Everyone,
If you're looking for a workaround, I have setup this on a raspberry pi https://github.com/AnotherDaniel/airprint-relay
Now it prints like a dream, clear and crisp barcodes including from Royal Mail, where they used to be horribly dithered.
Added benefit, your Zebra printer will become compatible with iPhones/iPads as well.
