### ISSUE TITLE
undefined reference to `httpConnect2' - CentOS : Updated #5120

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5125]
Update to  #5120 

NOTE:
1) I am not compiling cups source code, I am just calling httpConnect2 in my program 

2) All other functions link well for examples : cupsEncryption,cupsServer,ippPort link well with no issues..

3) the same httpConnect2 links well in Susi with the same cupos version cups-2.1.0

> I am calling the function like this

 

```
http = httpConnect2 (
    cupsServer(),
    ippPort(),
    NULL,
    AF_UNSPEC,
    encryption,
    1,/* blocking conn*/
    1000,
    NULL 
```
- I am suspecting NULL params , in the fiction definition of cups they are pointers
- probably CentOS treating NULL to pointer conversion differently ?
```
extern http_t		*httpConnect2(const char *host, int port,
				      http_addrlist_t *addrlist,
				      int family, http_encryption_t encryption,
				      int blocking, int msec, int *cancel)
				      _CUPS_API_1_7;
					  
```

**Comment by michaelrsweet** [comment]
> Note: Please follow-up on the cups-devel list, as the Github issue tracker is not intended as a discussion forum.

The NULL parameter is a) allowed and b) does not change the calling sequence to this function.

The function in question has been part of CUPS since 1.7. That it does not show up on CentOS points to a packaging problem of some sort there.

As we (Apple) do not provide the CUPS packages on CentOS nor do we provide support for CentOS issues, we can't help you here. You may find other developers that have run into similar issues on the (cups-devel mailing list)[https://lists.cups.org/mailman/listinfo/cups-devel], and of course since CentOS pulls its packages from Red Hat you might be able to contact them for assistance...
