### ISSUE TITLE
cupsGetDests2() lists local printers even if remote server specified

### ISSUE THREAD

**Issue by MarekKasik** [apple/cups#5135]
cupsGetDests2 function lists local printers even if it get "http_t *" parameter which points to a remote server. It seems to me that this is caused by the fix of the issue #4993. The new implementation does not use the "http" parameter at all.
Was it intentional?

**Comment by michaelrsweet** [comment]
The pointer should still be used, but keep in mind that support for non-local CUPS servers has been deprecated since 2.0 due to sandboxing and other security "features" preventing clients from accessing network printers directly - that's one of the reasons we added the new CUPS-Create-Local-Printer operation so that cupsd did all of the communications for you...

Investigating...

**Comment by michaelrsweet** [comment]
OK, I see how cupsGetDests2 is calling cupsEnumDests, which doesn't have a http_t * argument...  Will fix this for 2.2.5...

**Comment by zdohnal** [comment]
I'll just want to mention this issue breaks searching for printers in gnome (in control-center package).

**Comment by zdohnal** [comment]
I created patch, which does the trick (but it changes cupsEnumDests() and cupsEnumDestsBlock() API - it adds new parameter http_t *http - so I am not sure if it is right way to do it). https://github.com/apple/cups/pull/5136

**Comment by michaelrsweet** [comment]
[master 9554d4e74] `cupsGetDests2` was not using the supplied HTTP connection (Issue #5135)

**Comment by zdohnal** [comment]
Mike, I think commit didn't propagate to github master.

**Comment by MarekKasik** [comment]
Thank you for the fix.

**Comment by zdohnal** [comment]
Oh, nice, I can see it now - thank you for the fix Mike!
