### ISSUE TITLE
Please clarify Apache 2.0 license and if it applies to older versions of CUPS as well

### ISSUE THREAD

**Issue by joshgay** [apple/cups#5174]
I know that older versions of CUPS that have already been published under the terms of LGPLv2/GPLv2 are going to remain available for use under those same terms.  

However, I am wondering, if we are now also permitted to use older versions of CUPS under the terms of the Apache 2.0 license separately and instead of the LGPLv2/GPLv2 licensing terms?  

For example, hypothetically, if I have a project that includes code that was taken from release-2.0.0 but that code no longer appears in the newer versions of the CUPS code base (which is licensed under the terms of Apache 2.0), do I now have permission to use those files (the release-2.0.0 code) under the terms of the Apache 2.0 license or does that code remain exclusively for use under the terms of LGPLv2/GPLv2? 

Since Apache 2.0 and LGPLv2/GPLv2 are apparently incompatible licenses, this creates a hypothetical conundrum for me, since it means I could not patch older versions of the CUPS code base (or derivative works of the older code base) with code taken from newer versions of the code base. 

Your clarification and guidance on this matter is greatly appreciated and I thank you in advance for your time.

**Comment by Conan-Kudo** [comment]
@joshgay The obvious answer is obvious. You can't as the code before https://github.com/apple/cups/commit/e310189747c161ac6e737eedadf8f45d11bf2253 is GNU GPL, and code from that point onward is ASL 2.0.

It's the end of the line, bucko! 🤠

**Comment by michaelrsweet** [comment]
@Conan-Kudo I know you are joking, but please let me respond... :) Thanks!

@joshgay I've made my boss and our legal folks aware of your concerns; not sure what will come of it, but will update you as soon as I have an official answer about what we'll do for backporting/back-licensing bug fixes for previous versions of CUPS. As for making prior versions of CUPS available under the ASL2, Apple will not be doing that...

Generally speaking, any security patches we publish, e.g., for CERT advisories, are provided for multiple versions of CUPS and under the terms of the license for each version of CUPS. I don't see that changing, but that would mean GPL2/LGPL2 for earlier versions of CUPS and ASL2 for CUPS 2.3 and beyond.

Non-security bug fixes are currently just pushed to master (ASL2). While we don't post separate patch files to bug reports for specific CUPS versions, often the same changes will apply to older CUPS releases and those bug fixes are typically changes to a few lines of code and not major new content. I will try to get clarification from Apple legal on this situation so that we can clearly communicate which changes are available for use in older CUPS releases (under the GPL2/LGPL2) and which ones are considered new content/features.

**Comment by joshgay** [comment]
@michaelrsweet and @Conan-Kudo thank you both for your replies and also for escalating my concerns upward. The information you have provided is very helpful and I imagine any additional clarifications you can provide in the future on licensing of backports will also be appreciated by GNU/Linux distro developers and other CUPS package maintainers/distributors.

**Comment by zdohnal** [comment]
Hi Mike,
I see there is beta of CUPS 2.3.0, is there any update to this license matter from Apple side?

**Comment by michaelrsweet** [comment]
@zdohnal Sorry, not yet. I will ping the people involved to see if we can make some progress now that the holidays are behind us...

**Comment by zdohnal** [comment]
@michaelrsweet  Thank you Mike! I hope we can find solution which makes everyone happy!

**Comment by zdohnal** [comment]
@michaelrsweet Just adding proposition of solution from cups-devel mailing list - same solution use LLVM and I hope it is acceptable for Debian too (it is acceptable for Fedora).

LLVM uses exception of Apache license for GPLv2 [1] and adds this paragraph to license file:

In addition, if you combine or link compiled forms of this Software with software that is licensed under the GPLv2 (“Combined Software”) and if a court of competent jurisdiction determines that the patent provision (Section 3), the indemnity provision (Section 9) or other Section of the License conflicts with the conditions of the GPLv2, you may retroactively and prospectively choose to deem waived or otherwise exclude such Section(s) of the License, but only in their entirety and only with respect to the Combined Software.[2]

Just to mention, I cannot package CUPS 2.3 for Fedora until this licensing issue isn't solved :( .

[1] https://blog.gerv.net/2016/09/gplv2-combination-exception-for-the-apache-2-license/
[2] http://lists.llvm.org/pipermail/llvm-dev/2016-September/104778.html

**Comment by michaelrsweet** [comment]
@zdohnal Just a status update - we haven't forgotten about this issue and are still working it... :) FWIW, we're not going to release a 2.3.0 until the licensing issues are settled.

**Comment by michaelrsweet** [comment]
Still waiting... :/

**Comment by dankm** [comment]
> Still waiting... :/

Still waiting? I have a related technical and legal question. Are there now any plans to replace the GnuTLS dependency with something licensed Apache-2.0 or even more permissive, such as mbedTLS?

**Comment by michaelrsweet** [comment]
Yes. still waiting... :/

There are no plans to replace GNU TLS with anything else at this point. As for mbedTLS (PKA PolarSSL), I can't see us adopting it since the license options are Apache 2.0 without exceptions and GNU GPL (not LGPL), making it incompatible with a lot of existing code linking against libcups.

**Comment by OdyX** [comment]
I see v2.3rc1 has been released, but would you have good news news on this front?

As Debian/Ubuntu packager, I am worried, because for now I have only been able to upload any v2.3* releases to our `experimental` suite, "ignoring" this issue, but I (and Debian) really cannot ignore it for anything close to a stable release.

**Comment by zdohnal** [comment]
@OdyX Mike talked about it in his talk on PWG F2F in Lexington. CUPS 2.3 will stay on ASL 2.0 (actually I think I heard it will have an exception for GPL2.0 only as LLVM has, I cannot find it in slides though). As for the ones which will want to stay on 2.2.x - CVE fixes will have automatically old license and if you would want some fixes/features from 2.3.x to be in 2.2.x, file a ticket on github.

**Comment by OdyX** [comment]
@zdohnal The perspective of having CUPS 2.3+ licensed under "Apache + a GPL2-only exception" is good news, but we'll need to see this formally represented in the source. Barring this, CUPS 2.3+ cannot be made available in Debian unfortunately :-(

**Comment by michaelrsweet** [comment]
@OdyX The final 2.3.0 will include the exception text above, modulo any last-minute editorial changes the Apple legal folks might want (but I'm not expecting anything).

**Comment by joshgay** [comment]
Michael, can you please clarify if legal intends on a GPL 2.0-only exception or if it will use a GPL LGPLv2.1-only exception. The CUPS license dual licensed under LGPL and GPL. I never really understood this because the GNU LGPL 2.1 allows you to take the work and put it under the terms of the GNU GPL 2.0 (meaning you can change the license notices to just use the GNU if you wish). It states:

> You may opt to apply the terms of the ordinary GNU General Public License instead of this License to a given copy of the Library. To do this, you must alter all the notices that refer to this License, so that they refer to the ordinary GNU General Public License, version 2, instead of to this License. (If a newer version than version 2 of the ordinary GNU General Public License has appeared, then you can specify that version instead if you wish.) Do not make any other change in these notices.

So it would seem like an Apache 2.0 license with GNU LGPLv2.1-only exception might be  a better fit? I might not be thinking about this clearly. But perhaps it would be good to make sure whatever legal goes with that they are 1) choosing something that works for backporting patches to the LGPL/GPL dual licensed versions, 2) reminded of section 4 of LGPL 2.1?

**Comment by michaelrsweet** [comment]
@joshgay The exception we care about for CUPS is for GPL2-only software. I am not aware of any LGPL2-only software that links against libcups, and honestly our intent is pretty explicit and I don't want to change things now and introduce potentially another 18 months worth of delays... But for argument's sake if we ever do have an issue with a LGPL2-only project we can address it at that time.

Meanwhile we can have CUPS 2.3.0 with the GPL2 exception out to satisfy the 99.999%.

**Comment by joshgay** [comment]
OK thanks for the clarification. 

I was mainly thinking of software like Samba and other programs that are built against libcups.so. If I recall they do so in order to take advantage of security functions they get access to in their include<"cups/http.h"> directives. 

Presently, Samba, which is GPLv3 can link against libcups.so licensed under either Apache 2.0 or GNU LGPLv2. It could not be built against a verison of libcups.so that is licensed GPLv2-only since GPLv3 is not compatible with GPLv2. 

So while I might be wrong, but, I don't think Ubuntu or Debian would release any packaged backports or security updates to libcups.so if such patched versions forced it to became GPLv2-only. 

I don't actually know first hand of any other (non-GPLv2) programs besides Samba that are built against libcups directly like this, but I would have thought there would be others as well. Maybe @OdyX knows?

**Comment by michaelrsweet** [comment]
OK, we finally have the final approvals and I have pushed the changes:

[master 9fd3fb1dc] Add GPL2/LGPL2 exception to the new CUPS license.

And just to make sure this is clear, we will continue releasing security fixes and select other bug fixes (on request) against 2.2.x under the old (GPL2/LGPL2) CUPS license as well as the new CUPS license (Apache 2.0 + exceptions).

**Comment by OdyX** [comment]
Excellent news, thank you for making this exception happening!

**Comment by zdohnal** [comment]
Thank you for your hard work, Mike! And all others who made it possible!

**Comment by d235j** [comment]
@michaelrsweet the text of the exceptions at https://github.com/apple/cups/blob/7b6d49eec95fef100d017df6f1f577c72ca60577/NOTICE seems to only cover the GPL — is this intentional?

**Comment by michaelrsweet** [comment]
@d235j Yes, according to the lawyers the LGPL2 doesn't have the same compatibility problems that GPL2 has with Apache or GPL3... 🤷‍♂️
