### ISSUE TITLE
libusb-1.0 communicate with printer and then the cups can not print

### ISSUE THREAD

**Issue by liuxiaomeng2270** [apple/cups#5176]
I am developing a application(state monitor) which communicate directly to the printer. The communication function I run to libusb for it provided abunch of functions to read and write with USB.

The version of cups is 1.4.5
And the kernel version is 2.6.32

My system is linux redhat and when I plug in the printer, the system generate a link under /dev/usb/lp0.
When I run my application, which calls
1.libusb_init();
2.libusb_find_busses();
3.libusb_find_devices();
4.libusb_open_device_with_vid_pid();
5.libusb_free_device_list();
6.libusb_detach_kernel_driver();
7.libusb_claim_interface();
8.use libusb_bulk_transfer() to communicate with printer
9.libusb_release_interface()
10.and then libusb_attach_kernel_driver();
11,libusb_exit();

when the state monitor application exit, and I can not print any thing from CUPS.

the CUPS log shows can not communicate to printer(can not read any thing from printer).

I found when I call libusb_detach_kernel_driver(); the /dev/usb/lp0 link disappears and then I call libusb_attach_kernel_driver() the link /dev/usb/lp0 appears again. but still can not print anything.

when I run echo "somthing" > /dev/usb/lp0 in termail and cat /dev/usb/lp0 , I can get the return string from printer.

For I am not familiar with libusb, I can not figure it out why the printer(CUPS indeed) can print.

Any suggestion will be welcome.

Thank you.

**Comment by michaelrsweet** [comment]
Unfortunately, when it comes to the USB backend on Linux we are at the mercy of the Linux distros.

The current (libusb-based) USB backend *should* work in this situation, but IIRC the 1.4.x version of the backend did not work when the usblp kernel driver was loaded. Updating just the backend (or asking Red Hat to backport the fixes) is probably the best way to fix this issue.

**Comment by liuxiaomeng2270** [comment]
Hi, michaelrsweet.
Thank you for replying. But when I don't run the state monitor, and the /dev/usb/lp0 exists, I can receive data from printer and print correctly. It seems usblp is already loaded before I call libusb_attach_kernel_driver().

As what you just said "the 1.4.x version of the backend did not work when the usblp kernel driver was loaded" ,  do you mean that when /dev/usb/lp0 exists, CUPS backend can not communicate with printer?

I'm not familiar with usblp,

**Comment by michaelrsweet** [comment]
@liuxiaomeng2270 The usblp kernel module implements a character device that communicates with USB printers using the USB printer class, much like the USB backend does.

The CUPS 1.4.x backend did not support coexistence between libusb (the userland USB library) and the usblp kernel module, so it CANNOT work when the usblp module is loaded. I don't know what version of the USB backend is included with your Linux distribution, but if you want to use libusb separately to monitor the state of your printer you CANNOT use that USB backend - you need a newer version.

(There was a time when CUPS depended on the usblp driver, but as multifunction printers became more common and scanning became supported, we had to shift to using libusb instead so that you could scan and print at the same time.)
