### ISSUE TITLE
How to configure an IPP printer - documentation and error handling

### ISSUE THREAD

**Issue by zioalex** [apple/cups#5177]
In the https://www.cups.org/doc/network.html document page it is not clear to me how to properly configure an IPP printer.
I see 2 different options:
1. configure the server with a real printer driver
1. configure the server with a raw queue

In the option number 1 it should more clear that the client printer needs to be configured as RAW driver while in the option number 2 the real printer driver should be used.

Moreover configuring the printer, in option number 1, but with the real printer driver seems to work; the server receive the job and everything seems fine but no nothing is printed. No error at all in the logs.

**Comment by michaelrsweet** [comment]
Actually, for most IPP printers (including CUPS shared printers), the best option is probably to use the IPP Everywhere "driver" since that does the Right Thing ™ every time.

I'll keep this issue open to track updates to the documentation for this; we're past talking about raw queues and printer drivers when dealing with IPP.

**Comment by zioalex** [comment]
I didn't now about this driver. Now I configured it but sure the
documentation is lacking there.

**Comment by michaelrsweet** [comment]
OK, I've added a new "admin.html" help file and updated the (really out of date) "network.html" help file. Both are available in the Github repository for your review and will be part of the forthcoming CUPS 2.3 beta.
