### ISSUE TITLE
Implement HTTP notifier for cups

### ISSUE THREAD

**Issue by jcampbell05** [apple/cups#5182]
It would be useful for those wanting to implement basic subscription events from cups to support a basic HTTP notifier. The RSS one is quite complex to implement and dbus isn't known by all developers (in addition for both of these not containing documentation).

Given a subscription to `http://localhost:9000`, cups would send a POST request with the body containing a JSON payload with the event.

This should be fairly easy to implement given the curl c library is avaliable on almost every *-nix machine.

**Comment by michaelrsweet** [comment]
@jcampbell05 The existing notifier interface allow you to write your own http+json notifier quite easily, independent of the CUPS project. The testnotifier sources (part of the CUPS tarball) can be used as a template for such a notifier.

Years ago the IETF and PWG both tried to standardize a “push” mechanism using HTTP (although in our case we used the IPP message encoding and not JSON which hadn’t yet become as popular) - there was so little interest that we dropped the effort. Apple hasn’t received a single request for us to revive the effort in the almost 20 years since,,,

Until there *is* a popular, standardized HTTP push mechanism I can’t see us adopting or supporting as part of the CUPS project...

**Comment by jcampbell05** [comment]
So we actually need this in our cloud printing solution at the printtapp.com 

We needed an automated way of ingesting the events from cups for our business application: 
- `mail` isn't suited for this.
- The RSS one is too complex when all we need is to know what event was triggered.
- DBus requires X11 (not available on servers or recommended to install by canonical) and not the easiest to use in other languages (even if you get over learning curve the libraries in python for example aren't easy to get working)

So today we build and open-source our MVP implementation of a HTTP JSON notifier we hope can serve for a future implementation in the cups library. 

You can see it here:
https://github.com/AIWIP/cups-http

It currently mirrors the IPP event in JSON format to match the spec (With the exception of the subject and message fields we added from the mailto notifier), to keep things simple and standardized.
