### ISSUE TITLE
cupsSendRequest does not wait after sending "Expect: 100-continue"

### ISSUE THREAD

**Issue by DavieV** [apple/cups#5248]
In cupsSendRequest() the HTTP header is first sent using httpPost(). This header contains an "Expect: 100-continue" message, which implies that the client may wait for the server to respond with a "100 Continue" message before sending the rest of the request. However, immediately after sending the header the rest of the IPP request is sent as well using ippWrite(), and then only after this does the client begin to "wait" for the "100 Continue" response.

I looked through some of the history of the project and it seems that the wait used to be correctly placed between sending the header and the rest of the request, but the order was changed at some point.

I think the order should either be fixed and the wait should be put back in the middle, or the "Expect: 100-continue" field should be removed from the header. In the current state it is being used in a way that it was not intended and defeats the purpose of the field.

**Comment by michaelrsweet** [comment]
IPP servers cannot always evaluate the security requirements of a request until the IPP request has been read, and the 100-continue (or 401, etc.) status can come back at ANY time while the client sends its request, so the current behavior is as intended and expected. (pun intended)

We could conceivably check immediately after sending the post, but we cannot wait indefinitely for a response since servers are not required to support the Expect header (grumble grumble). And since most printers need to see the IPP request message to determine the scoping anyways (this isn't REST where you end up with different endpoints for different functions) that change would potentially cause more problems than it solved...

So sorry, but not to be fixed.
