### ISSUE TITLE
extend the detection of preformated datastream (raw-printing)

### ISSUE THREAD

**Issue by frazhome** [apple/cups#5294]
to implement the  Feature "FUTURE: Remove printer driver and raw queue support. #5271" it is necessary to extend the detection of preformated datastream.

the other possibility is to extend the mime.type/mime.convs for preformated datasteam.

as example ZPL/IGP:
mime.type
application/zpl			contains(0,128,"^XA")
application/igp			contains(0,128,"^CREATE;")

mime.conv
application/zpl        application/vnd.cups-raw        0       -
application/igp	       application/vnd.cups-raw	       0       -

for each type of datastreams a solution is necessary. 
maybe CAB-Printers and so on

regards
Franz

**Comment by michaelrsweet** [comment]
@frazhome I'm sorry, but we are not going to do this.

Raw printing is not something we want to encourage. And frankly there is little reason to need it - serial and USB label printers can accept the raw labels directly, and for AppSocket you can just use the "nc" program (or any number of socket wrapper programs). If you want CUPS to manage your label printers, use drivers (for now), devices/programs that emulate IPP, or actual printers that support IPP/IPP-USB so that your applications can supply a standard format.

**Comment by frazhome** [comment]
Sorry Michael,

maybe you do not understand the reason for this.
I need the "it is preformated" detection to configure the printer with the necessary printerdriver.

this is only a fallback for legacy application.

Maybe you are living in a perfect world.
By I have to deal with a lot of printers which do not understand IPP/IPP-USB.

I am often happy when the devices are communicate via lpd!

regards
Franz
