### ISSUE TITLE
/etc/cups/subscriptions.conf should live in /var

### ISSUE THREAD

**Issue by tvw** [apple/cups#5313]
I have /etc under version control and this file is automatically changed by cups, which means, that it stores data rather than configurations.

Even the documentation says "This file is not intended to be edited or managed manually." because it is maintained by cupsd.

So I think, /etc is the wrong place to store such information. A better place would be /var (sic!)

**Comment by michaelrsweet** [comment]
This will not be changed for the current generation of CUPS. Only Linux follows the FHS and it is entirely in the distributions power to change the default.

Also see the discussion in the [previous issues](https://github.com/apple/cups/issues?q=is%3Aissue+fhs+is%3Aclosed) - at some point in the future we’ll likely change to a more efficient binary format for such things...

**Comment by tvw** [comment]
@jsmeix 
The issue is not, how the configs are changed but what they contain.

cups/subscriptions.conf has a config called "ExpirationTime" or "NextEventId".

This looks to me like state and not like a configuration.

**Comment by tvw** [comment]
@michaelrsweet 

But even BSD has /var/tmp

@jsmeix 

The issue is not, how the files are changed but what they contain:

subscriptions.conf contains things like "ExpirationTime" and "NextEventId" etc.

This does not look like configurations which tell cupsd something about the environment it runs in but like state it maintains for itself. But /etc is absolutely the wrong place for maintaining state. Otherwise a database engine could also store its table files under /etc.

**Comment by fergald** [comment]
Just ran into this when I decided it's time to keep etc under version control. It's very annoying.

NextEventId 1117

is not configuration it's state and shouldn't be in a config file. I have one machine in my house where /etc/ is read-only and /var is a memdisk. It's that way to protect the (old) SSD from excessive wear. It's not running cups but if it was there would presumably be trouble.

It's fine have machine-generated and machine-maintained configs in /etc but that's a different thing.

**Comment by nxg** [comment]
I appreciate this, along with the numerous other reports of this as a problem, is a `wontfix`, and it's reassuring that the comment from @michaelrsweet at least leaves open the possibility of this changing in a future version of CUPS.

As notes for that future change, however, I'll highlight that this isn't about the FHS specifically, but about BSD, general/historical unix and specific macOS standards.  hier(7) on macOS says that `/etc` is for ‘system configuration files and scripts’, and the Apple [Filesystem Programming Guide](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW7) says that `/etc` ‘Contains host-specific configuration files.’  I do not agree that there is any reasonable definition of ‘configuration file’, on any unix flavour, which includes state information such as `ExpirationTime` and `NextEventId`, which are initiated by the daemon rather than the administrator.

  * I appreciate that there's some attraction to keeping this state information nearby the configuration information; that being attractive doesn't make this OK.
  * I appreciate there isn't a pre-ordained standard location for this, but `/var` is (according to hier(7)) for ‘multi-purpose log, temporary, transient, and spool files’, which seems to clearly indicate that this sort of state information should go _somewhere_ under there (and `/var/spool` even says ‘misc. printer and mail system spooling directories’, so is a very obvious location for this).

If I instruct the daemon to change its configuration and as a result it rewrites a file in `/etc`, that's fine – that's my configuration change.  Bluntly, the daemon shouldn't be scribbling in my configuration files on its own initiative.
