### ISSUE TITLE
systemd socket activation and printing

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#5319]
We have a bug report in Debian; #899259:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899259

The essence of it is that, when printing to a queue, socket activation does not work and, after 'lp -d <file>'  or 'lpr <file>,  cupsd fails to close the listen  sockets. The report does contain a portion of an error_log which records this. Socket activation is reported as working in CUPS 2.2.6-5.

The CUPS version is 2.2.7-5. Note that the Debian version has backported "Restart=on-failure" from Issue #5297.

Regards,

Brian.

**Comment by paraisoJ** [comment]
Samsung Galaxy J3 (2016)
SM-J320FN

**Comment by paraisoJ** [comment]
My wish list

**Comment by michaelrsweet** [comment]
OK, so the issue is that, after printing something, that cupsd does not idle exit after 60 seconds?

Keep in mind that what cupsd considers idle may not be your expectation - if printer sharing or the web interface is enabled, if a job is still being processed, or other child processes are still active, then cupsd will not idle exit (by design).

Anyways, from the limited log snippets in the Debian bug report, it looks like select_timeout() is returning 86400 (one day) because there is nothing to do and we don't wake up just to write out dirty files. I can look at updating the code to reduce the timeout when we would normally idle exit, but (as mentioned in my recent OpenPrinting presentation) doing an idle exit isn't always the optimal solution anyways.

**Comment by debiantriage** [comment]
On Mon 04 Jun 2018 at 16:46:49 +0000, Michael R Sweet wrote:

> OK, so the issue is that, after printing something, that cupsd does
> not idle exit after 60 seconds?

That about sums it up; the behavior is in contrast to using lpadmin,
lpstat etc and getting idle exit after 60 seconds

> Keep in mind that what cupsd considers idle may not be your
> expectation - if printer sharing or the web interface is enabled, if a
> job is still being processed, or other child processes are still
> active, then cupsd will not idle exit (by design).

Speaking for my own tests: the web interface was not enabled, there were
no jobs being processed and no printer sharing. Indeed, for the lpadmin
command the log shows

> Printer sharing is off and there are no jobs pending, will restart on demand.            
> Scheduler shutting down normally.

Child processes? I wouldn't know what I was looking for.

> Anyways, from the limited log snippets in the Debian bug report, it
> looks like select_timeout() is returning 86400 (one day) because there
> is nothing to do and we don't wake up just to write out dirty files. I
> can look at updating the code to reduce the timeout when we would
> normally idle exit, but (as mentioned in my recent OpenPrinting
> presentation) doing an idle exit isn't always the optimal solution
> anyways.

FTR:

https://ftp.pwg.org/pub/pwg/liaison/openprinting/presentations/cups-plenary-may-18.pdf

If a fuller log is required, I'm sure Francesco Poli would provide one.

Regards,

Brian.

**Comment by michaelrsweet** [comment]
OK, near as I can guess the issue is that Browsing (sharing) is enable by default in Debian (sigh...) which means that the idle exit timeout will not kick in as soon as there is a print queue (== hey we are doing printer sharing), even if that queue is not being shared itself (printer sharing has both a global on/off switch as well as the per-printer switch...)

Right now the code for idle exit isn't smart enough to know the difference between printers that are shared and printers that are not shared. Will look some potential changes that don't cause a performance regression...

**Comment by michaelrsweet** [comment]
A temporary workaround is to run:

    cupsctl Browsing=No

to restore the CUPS default setting.

**Comment by michaelrsweet** [comment]
[master 9fc5c8d42] Support idle exit, even when printer sharing is enabled but no printers are shared (Issue #5319)

(and this is why I don't like Linux distros changing the CUPS defaults...)
