### ISSUE TITLE
cups shouldn't accept printer hostnames that don't resolve to IPs

### ISSUE THREAD

**Issue by yurivict** [apple/cups#5384]
I've setup the printer in cups, but the hostname doesn't resolve to IP.
It says:
> Connection: lpd://KMBA5BCB.TheLanName.local/print

but ```KMBA5BCB.TheLanName.local``` can't be resolved, and all jobs get into ```Unable to locate printer``` state.

cups shouldn't just create a printer with invalid hostname.
cups should use the IP address in such case to work around this problem, and notify the user. Or, better, ask the user if that's what he wants to do.
When cups scanned printers, it did have the IP address from which the response was sent.

Since printers are a very ubiquitous device, it can be expected that some networks/devices aren't fully setup, like in this case name resolution isn't working. cups should work around such common problems when possible. In this case it is certainly possible.

Original report: https://github.com/apple/cups/issues/5383

**Comment by michaelrsweet** [comment]
This just isn't something we can handle in the general case since many backends use things other than hostnames (e.g. the SMB backend). And since name resolution and networking issues can be temporary, it would not be appropriate to prevent a queue from being added just because the printer cannot be resolved or reached at that time.
