### ISSUE TITLE
5s delay after each printjob on USB label printer 

### ISSUE THREAD

**Issue by luxlux** [apple/cups#5399]
I have here 2 USB connected label printer models: 

- IMAJE (/Markpoint/DATAMAX) MP4 Compact (language: Labelpoint - lp ) Vid: 0x092e Pid:1
- XPRINTER XP-460B (language: ZPL & TSPL) Vid: 0x2d84 Pid: 0xb528

I have tried it with MAC OS 10.9(Cups 1.7.2), MAC OS 11.3(Cups 2.2.5) and with Linux Mint (Cups 1.7.2).

I have installed the printer using the cups webinterface as pure RAW device without a ppd file.

If I send a (very simple) printjob using the command (multiple times):
`lp test.lp -d MP4`
or 
`lp test.tspl -d XPRINTER`

there is a delay of about 5 seconds after each print.
**How can i eliminate this delay?**

On Linux Mint i found out using `cat test.lp > /dev/usb/lp0 `  (after making /dev/usb/lp0 writeable for others) does not produce this issue. All jobs will be printed without delay. I guess this way omits cups.

**But there is no /dev/usb/lp0 on Mac OS. Is there an other way to send data directly without the delay?**

**Comment by michaelrsweet** [comment]
I believe this is the 5-second back-channel read timeout. When we finish sending print data we tell the read thread to stop, which takes up to 5 seconds to clear.

On Linux you can add a quirks file specifying that the printer is unidirectional - use the "lsusb" command to get the vendor and product ID numbers and then create a file called /usr/share/cups/usb/myprinters with the following line repeated for each printer:

    0xVVVV 0xPPPP unidir

The "VVVV" is the first hex number reported by lsusb, and "PPPP" is the second.

On macOS there is no equivalent file - there we depend on printer vendors to provide USB class drivers that provide this sort of behavior.

An alternative is to submit all of the print files in a single job, e.g.:

   lp -d MP4 test1.lp test2.lp test3.lp

The delay between files will be eliminated this way.

**Comment by luxlux** [comment]
Thanks, this worked for me on ubuntu.

Is there not possibly an other way or work arround for mac os?
There are other folders like /usr/share/cups/drv.
Is it may be possible to write a minimalistic raw driver for that device and put it there? (or to upload it to apple? The chinese manufacturer looks like not interested in doing this, by themself.)

I even have the problem (on mac OS 10.9), that the Xprinter ZJ-460B often will not be recognized as connected. Sometimes it will, but only seldom.

I also have a second question about unidirectional and bidirectional:

These label printers can be requested for some data. In example with !S1 some status data ( like the label taken sensor, or the paper state) can be requested from the MP4 Compact. If i connect the printer by network and access it using the telnet client, I get the answer in the next line. But how to get such data using USB and cups / lp?

**Comment by michaelrsweet** [comment]
The way to do this on macOS involves a codeless kext that points to a USB class driver, and the kext needs to be signed with a kernel code signing certificate (so not something you can probably do yourself...) If the manufacturer has provided a driver for macOS then you will have this, otherwise no...

Random "discount" hardware often shows problems on the USB bus, and this often causes disconnects on macOS and Linux...

WRT getting status data back, CUPS is not a raw printing system that gives you bidirectional access to a printer. A printer driver would be able to query the status data and convert it to a form that CUPS can relay to a client/application (such as a printer-state-reasons keyword) but NOT an application submitting a file to CUPS.
