### ISSUE TITLE
"filter failed" printing blank page

### ISSUE THREAD

**Issue by Alex1681** [apple/cups#5400]
Hi all,

Since I have migrate to new cups server I have some printers whith this error : 
Command Line Error: Wrong page range given: the first page (1) can not be after the last page (0).
D [23/Sep/2018:03:49:11 +0200] [Job 92657] The print file is empty.
D [23/Sep/2018:03:49:11 +0200] [Job 92657] PID 7928 (pdftops) stopped with status 99!
D [23/Sep/2018:03:49:11 +0200] [Job 92657] PID 7929 (pstops) stopped with status 1!
D [23/Sep/2018:03:49:11 +0200] [Job 92657] PID 7926 (/usr/lib/cups/filter/pdftops) stopped with status 1.

Some printers are OK and some are present with this error when my application ask to print a empty file (empty pdf file).

The /var/spool/cups is growing and I have to clear the queue .

With other document I have no problem.

 Version : 
cups-lpd-1.6.3-35.el7.x86_64
cups-filesystem-1.6.3-35.el7.noarch
cups-1.6.3-35.el7.x86_64
cups-libs-1.6.3-35.el7.x86_64
cups-filters-libs-1.0.35-22.el7.x86_64
cups-filters-1.0.35-22.el7.x86_64
ghostscript-cups-9.07-28.el7_4.2.x86_64
cups-client-1.6.3-35.el7.x86_64

Oracle Linux Server release 7.4
4.1.12-112.16.4.el7uek.x86_64

**Comment by imsedgar** [comment]
On Fedora 28 we had a similar problem previous week, which was caused by an update of ghostscript, and solved by another update of ghostscript. For more information about the Fedora solution see
https://bodhi.fedoraproject.org/updates/FEDORA-2018-c39ae23dc8
https://koji.fedoraproject.org/koji/buildinfo?buildID=1145180
https://koji.fedoraproject.org/koji/packageinfo?packageID=740

For RHEL there exists also a bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1627959

You may need to wait for updates, or build you own package (you may use source rpm from Fedora 28 on koji (linked above), but I don't know if it is suitable for Oracle Linux.

**Comment by Alex1681** [comment]
Thanks imsedgar.

I will wait for updates.

Regards,

Alexandre

**Comment by caot** [comment]
For el7 centos or rhel, it worked after install the follows:

# yum install ghostscript

Referring: https://askubuntu.com/questions/601836/cups-pdf-prints-a-blank-page
