### ISSUE TITLE
Documentation of the meaning of failed prints in regards of the job-policy

### ISSUE THREAD

**Issue by JackGrinningCat** [apple/cups#5404]
Hi, 

I'm trying the job policy abort-job and now I'm wondering when that can happen?

I got an ipp printer which is reachable while registration but at the time of printing not.
I expected a timeout of around 300 seconds for the requests as documented 
> Timeout seconds
>     Specifies the HTTP request timeout. The default is "300" (5 minutes).
and a job state transition to ABORTED sometimes after that timeout.

I'm checking now since some time but the the printer never leaves the state of
printer x now printing job 
printer is not responding

Is that the expected behavior?

**Comment by JackGrinningCat** [comment]
After reading the code in job.c I did understand that there is an **MaxJobTime** which used to cancel a running jobs with the default behavior based on the job-policy. That would be 3 hours (3 * 60 * 60). 

I think that is a good timeout for running jobs. Sometimes the printer can be in use. 
The unreachable use-case should be a different one and be handled as something that could go wrong and possible lead to an error that aborts the job.

I take this issue as question or discussion point.

**Comment by michaelrsweet** [comment]
Disabled/stopped printer states are considered transient, so they won't cause a job to be aborted (otherwise you'd lose a lot of print jobs on some printers...)

**Comment by JackGrinningCat** [comment]
Actually i took the job-policy because i thought i understand what a failed job could be, and i see that I'm wrong here. Could you point at a list of a definition what a failed job is? 

I miss that now after reading [cupsd.conf](https://www.cups.org/doc/man-cupsd.conf.html) or googling for that definition...

**Comment by michaelrsweet** [comment]
OK, so right now a failed job (for purposes of the printer-error-policy) is one that either:

a) Cannot be sent to the printer because of a permanent error - printer responds with "not found" or "forbidden" or "document format not supported"
b) Cannot be sent due to an error during submission (i.e. we can connect and start sending the print data, but we get a write error)
c) Causes one or more filters to crash

There is a sub-category of "temporary" failures (not accepting jobs, printer stopped, unable to connect, document format errors where we can retry with raster data, authentication failures, etc.) that bypass the printer-error-policy setting. In the case of connection or submission issues, we either keep retrying on the same printer or retry on the next printer in the class (for jobs submitted to a class). Document format errors lead to the job being retried using another format, and authentication issues hold the job pending re-authentication.

Conceptually we could update the printer-error-policy to also apply to (temporary) connection/submission failures, although I'm not sure how useful that would be. *Or* we could add a separate retry policy that specifies how long/whether to retry connections/submissions to the printer. *Or* we could simply update the "contimeout" URI option to specify a hard timeout where the default is to try connecting forever but specifying a hard timeout will cause the job to fail if the connection isn't made within the specifies interval. That, too, could be setup as an environment variable (CUPS_CONNECTION_TIMEOUT) that could be passed from cups-files.conf to the backends (overriding the default no-timeout setting).

**Comment by JackGrinningCat** [comment]
First, thanks for the list. That already helped me. 

I tried to point out some of my opinions:

> There is a sub-category of "temporary" failures (not accepting jobs, printer stopped, unable to connect, document format errors where we can retry with raster data, authentication failures, etc.) that bypass the printer-error-policy setting.
> Conceptually we could update the printer-error-policy to also apply to (temporary) connection/submission failures, although I'm not sure how useful that would be. 

Those temporary bypassing the error-policy are the hard to discuss and handle. I would prefer to do this in another issue on itself to list all temporary cases and the wanted way to handle them.

Besides that they are the most frustrating to me. If the user (here the grand me 👑 ) cannot find an insight to the underlying means. 
To see that a printer was disabled by a user that fiddled around some settings is depressing when you tried to see why cups is comfortable waiting without a note to you as user. Or other way around me as a tester trying to get the right states that the printer aborts a print job due to temporary reasons.

> Or we could add a separate retry policy that specifies how long/whether to retry connections/submissions to the printer. 

I would prefer this! This seems the easiest one. Even if it might not avoid those other cases to discuss or handle. But it's a good and easy understandable case. Printer is not reachable after three times a 300 seconds, then CUPS will let the error-policy decide how to handle this case.

> Or we could simply update the "contimeout" URI option to specify a hard timeout where the default is to try connecting forever but specifying a hard timeout will cause the job to fail if the connection isn't made within the specifies interval. 

hmm, do dot know. I didn't use it before. 

> That, too, could be setup as an environment variable (CUPS_CONNECTION_TIMEOUT) that could be passed from cups-files.conf to the backends (overriding the default no-timeout setting).
Good to know how that's working! 

Thanks again for your feedback and the options.

**Comment by michaelrsweet** [comment]
[master b167c7fcf] Clarify meaning of printer errors (Issue #5404)
