### ISSUE TITLE
Redesign the CUPS Admin Webpage

### ISSUE THREAD

**Issue by Mannshoch** [apple/cups#5426]
Every time I need to use the CUPS admin Page. I feel like back in the year 2000.
It should be possible to Manage Printers and Classes and their rights from the Web more easy.
A dynamic help per Page would also be nice.
I would like to have a paper manager where i could setup the Paper with all parameters globally, and then add them to the Printers. And If a Print job is setup only the set-up paper could be chosen.

**Comment by michaelrsweet** [comment]
While I appreciate what you are asking for, the web interface is currently in maintenance mode and we have no plans of enhancing it.

In particular, the move towards "driverless" printing with IPP Everywhere and AirPrint puts the management of such things on the printer and not on the server, since the Client gets the list of supported media from the printer and not the printing system.

**Comment by Mannshoch** [comment]
In my opinion a printer should have no authority about paper except the max./min. width and maybe some paper settings. But not what format between max./min. width or the length.

What Paper I have is my only authority. 

I do not like to transfer the whole Management to the Printer.

**Comment by michaelrsweet** [comment]
All current printers report what media is loaded and typically provide their own web interface for configuring what additional media should be reported as "available" (which is therefore under your control...)

Moreover, CUPS has NEVER provided ways to limit media - we've always shown the full list reported by the driver. The kind of control you are asking for is typically provided by managed printing services.
