### ISSUE TITLE
CUPS removes job from queue but printer doesn't print

### ISSUE THREAD

**Issue by NeuralFlux** [apple/cups#5441]
When the printer's out of paper, CUPS doesn't store the job, instead it removes it. The printer also doesn't print, since there's no paper. So is there a way to get the status code for a job or something likewise?

**Comment by zdohnal** [comment]
Hi,

what is your CUPS version? What is your printer uri?

**Comment by NeuralFlux** [comment]
CUPS 2.2.7
URI socket://10.196.0.99:9100

**Comment by jsmeix** [comment]
@NeuralFlux 
without details I guess CUPS does not "just remove" the job.
I think CUPS can successfully submit the print job data to your printer
so that the job is "successfully printed" from CUPS's point of view and
finally CUPS removes the print job data of "successfully printed" jobs,
cf. "What is a CUPS backend and how does it work?" in
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell

For details what actually happens in your particular case
inspect your CUPS log file (in debug mode), cf.
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue

You may also have a look at
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
what you might do to debug this issue with your printer.

**Comment by NeuralFlux** [comment]
Thank you so much for helping!
