### ISSUE TITLE
Sharing a virtual printer between unix-windows systems

### ISSUE THREAD

**Issue by GreatBahram** [apple/cups#5469]
Hi, 
I've written a virtual printer based `tea4cups` which you guys introduced it to me, and I also wrote [simple PPD](https://github.com/GreatBahram/simple-cups-backend/blob/master/sample.ppd) file for that printer. Everything is fine for unix* systems. But when I want to share it via windows users, it needs a driver and windows default generic drivers does not suit me. How can I solve this problem?

It does not matter what sharing protocol is I mean `IPP`, `SAMBA` or even `Bonjour`. I used some cups' filters and windows drivers don't care about those filter, and they send `application/octet-stream` files to spooler directory. I don't want that, I want to be like unix system output which is `pdf`.
* Can I write inf file based on PPD file?
* Or any other suggestions are welcomed.

Please let me know, if there is any misunderstanding here.
Thanks

**Comment by michaelrsweet** [comment]
Sorry, there is no standard way to get PDF from a Windows client.

**Comment by jsmeix** [comment]
@GreatBahram only FYI you may have a look at
https://en.opensuse.org/SDB:Printing_from_Windows_to_Linux

I think I vaguely remember from ancient past that there was
a more or less generic driver at least in older Windows versions
that produced more or less generic PostScript and I think that
driver was one for an Apple LaserWriter PostScript printer, cf.
https://en.wikipedia.org/wiki/LaserWriter
so that by using such kind of driver under Windows
the Windows client would send more or less generic PostScript
to CUPS which could (hopefully) "just work" because PostScript
is "The traditional printing data format", cf.
https://en.opensuse.org/Concepts_printing

At least under Linux generic PostScript is still a well supported
standard print job data format.
