### ISSUE TITLE
Cups daemon  notifies avahi about printers before it starts responding to clients cups queries on port 631

### ISSUE THREAD

**Issue by kabassanov** [apple/cups#5480]
Hello,

We use a cups server (2.2.8) with an avahi daemon for printer sharing.
We noticed that every time cupsd reloads its configuration (or when we restart it), remote linux clients (cupsd + avahi + cups-browsed) loose one or two printers from the server. 
Some tests we made showed (in cups-browsed logs) that this issue concerns printers first rediscovered by the client. In addition, it seems that client tries to connect on server port 631 in order to get the PPD file, but server is not ready to reply yet.  Printers never reappear (except if we restart cups-browsed on client side).     

Well, it is also possible that there is some mess on the client side (concurrent remove/add of the same printer), isn't it?

My idea is to put some initial delay before cups server starts sending notifications to avahi in order to be sure it has already started servicing cups on port 631... But where?

[cups-browsed-extract.txt](https://github.com/apple/cups/files/2759325/cups-browsed-extract.txt)

**Comment by michaelrsweet** [comment]
Not much we can do right now as cupsd responds to client connections from a single thread, and Avahi's threading support is fairly primitive, so we have to register services from the same thread that handles client connections... That registration process is (unfortunately) slower than it needs to be...

I'd file a bug against cups-browsed in the [cups-filters](https://github.com/openprinting/cups-filters) project - they might want to "debounce" the printer discovery and retry when the initial connection to the server times out. Or better yet, not auto-create every network queue it finds since CUPS will auto-create on demand these days... :)
