### ISSUE TITLE
IPP backend might not support copies when printer doesn't indicate support

### ISSUE THREAD

**Issue by j39m** [apple/cups#5541]
## Observed behavior

We're testing CUPS behavior on Chrome OS with the [internal fork of CUPS 2.2.8](https://chromium.googlesource.com/chromiumos/third_party/cups/). When we print to a virtual IPP printer that doesn't report copy support (i.e. provides no values for `copies-default` and `copies-supported`), we are unable to get the printer to actually produce multiple copies.

## Expected behavior

We thought the ipp backend might be able to resend the job multiple times [as it does for printers supporting HTTP < 1.1](https://chromium.googlesource.com/chromiumos/third_party/cups/+/a79fc1297ecbdf2a3c249715b82e3702652705af/backend/ipp.c#1412). But since our print job arrives via stdin, [`copies_remaining` gets jammed to `1`](https://chromium.googlesource.com/chromiumos/third_party/cups/+/a79fc1297ecbdf2a3c249715b82e3702652705af/backend/ipp.c#1328) and we observe only one copy output from our virtual printer.

**Comment by michaelrsweet** [comment]
@j39m It is the responsibility of the Client to produce copies in this case. But the IPP backend just isn't that smart and can only make copies if you are printing a "raw" file (i.e. one that doesn't involve any filtering) - otherwise it assumes that the filters took care of creating the copies.

All of the major IPP-based printing certification standards (AirPrint, IPP Everywhere, Mopria, Wi-Fi Direct Print Services) require IPP printers to support copies for things like JPEG and PDF, but not for other formats like PCLm (HP's PDF raster subset), PWG Raster, Apple Raster, etc. So you need to take care of making copies in the client-side filters.
