### ISSUE TITLE
Add a Include directive in cupsd.conf

### ISSUE THREAD

**Issue by spaceone** [apple/cups#5556]
During a security update the Include directive in cupsd.conf was removed:
https://security-tracker.debian.org/tracker/CVE-2018-4181

It seems that the Include directive was not itself vulnerable but it was an easier code change.
It would be nice to re-add the Include directive!

(we had dynamic extensible configration files which don't work anymore in our customer environments).
```
E [08/Jan/2019:10:56:53 +0100] Unknown directive Include on line 630 of /etc/cups/cupsd.conf.```

**Comment by spaceone** [comment]
See also https://github.com/apple/cups/commit/d47f6aec436e0e9df6554436e391471097686ecc

**Comment by michaelrsweet** [comment]
The issue is that the cupsd.conf file can be updated remotely. If you can reference a conf file from cupsd.conf, then you can potentially get untrusted configuration settings loaded, which is a security concern.

Also, updating a referenced file requires a manual restart of cupsd while updating cupsd.conf (through a cupsd socket connection) does an automatic restart.

Sorry, we have no plans of bringing the Include directive back.

**Comment by stephen-mw** [comment]
I respect your decision to remove this setting because of its documented security concerns.

But now it's much harder to manage the `cupsd.conf` file programatically.

For example using ansible I have to use a regular expression to match opening and closing `<Policy>...</policy>` tags in order to change the contents.

Before I could just have ansible manage an additional `cupsd_ansible.conf`.

Have you given some thought of how system administrators should programmatically manage this configuration file?

It's easy to create a block at the end of the file, but now you've got duplicate policies and cups complains, and it's not actually clear to me which policy configuration cups uses when there is a duplicate. The one at the beginning or the one at the end? If cups reliably uses the last `<policy>` block and ignores previous ones, we can just append our managed configs to the end of the `cupsd.conf` file.
