### ISSUE TITLE
Build error in scheduler/type.c 

### ISSUE THREAD

**Issue by dheeraj135** [apple/cups#5568]
Platform: Ubuntu 19.04

```make``` command fails with this error:
```
Compiling type.c...
type.c: In function ‘mimeAddTypeRule’:
type.c:531:9: error: ‘num_values’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      if (num_values < 2 || (size_t)length[1] > sizeof(temp->value.stringv))
         ^
cc1: all warnings being treated as errors
```
I suggest this patch: 
[0001-Fix-uninitialized-error-in-type.c.patch.txt](https://github.com/apple/cups/files/3101198/0001-Fix-uninitialized-error-in-type.c.patch.txt)

**Comment by michaelrsweet** [comment]
What compiler are you using? I can't reproduce.

**Comment by dheeraj135** [comment]
I am using ```cc``` and ```c++```.

**Comment by dheeraj135** [comment]
@michaelrsweet Are you able to reproduce this error?

**Comment by michaelrsweet** [comment]
@dheeraj135 As I said above, no.

**Comment by michaelrsweet** [comment]
Well, hopefully this fixes the issue:

[master d86153a94] Make sure "num_values" is always initialized since newer versions of GCC will (incorrectly) error out on this...

Near as I can guess, the version of GCC bundled with Ubuntu 19.04 incorrectly thinks that "num_values" is not initialized for the string/istring rule case. Clang and older versions of GCC correctly recognize the potential code paths and know that num_values is always initialized for them.
