### ISSUE TITLE
Queuing multiple jobs on a print server with the ipp backend

### ISSUE THREAD

**Issue by IslandCow** [apple/cups#5575]
If CUPS is setup to send jobs to a print server, should it be possible for CUPS to queue multiple print jobs on that server?  It appears that the ipp backend will not queue multiple jobs where the print server reports the following state:

printer-state: idle
job-state: pending-held

Is this the desired behavior?  It seems that if printer-state is processing, the backend should wait but if the printer-state is idle, it should continue to send jobs to the print server.  In IPP INFRA in the printer-state table, this would appear to be a possible situation.

http://ftp.pwg.org/pub/pwg/candidates/cs-ippinfra10-20150619-5100.18.pdf

**Comment by michaelrsweet** [comment]
That is not how CUPS is setup to relay jobs by default since then the local user would lose the ability to cancel those jobs and there is a risk of job loss on the server. Moreover, when printing to a class we will switch to the next available printer if a printer is busy. The "waitjob" option (ipp://host/resource?waitjob=no) can be used to override this behavior and allow cupsd to process the next local job in the queue (with the previously mentioned caveats).

Longer term we would like to support this automatically, but doing so will require some architectural changes that will break printer drivers, so you won't see this until printer drivers are gone...
