### ISSUE TITLE
webinterface GSSAPI  auth broken in cups >= 2.2

### ISSUE THREAD

**Issue by kenshin33** [apple/cups#5596]
As the tite states, the web interface does no longer work if authentication is required and Negotiate is set.

For example after the last step in modifying a printer the interface hangs. Tcpdump shows no reply after the post (except for the keepalive packets).
cupsd and admin.cgi cpu usage on the server goes up.
Debuggin shows an infinit loop in admin.cgi, precisly the  while (response == NULL) in cupsDoIORequest  (cups/request.c)

Basic auth works fine 
OS :debian stretch 
Cups: 2.2.10 (source for buster rebuilt with debuging enabled)

**Comment by michaelrsweet** [comment]
@kenshin33 We'll need debug logs from the system in question. (cupsctl --debug-logging)

**Comment by kenshin33** [comment]
tryin to modify the default options of a printer
[error_log.old.gz](https://github.com/apple/cups/files/3284171/error_log.old.gz)

**Comment by michaelrsweet** [comment]
@kenshin33 OK, I'll need to see your cupsd.conf file as well - the admin.cgi program is using Peer Credentials for some reason, instead of Negotiate.

**Comment by kenshin33** [comment]
Here it is  (removed identifying information): 
[cupsd.conf.gz](https://github.com/apple/cups/files/3399460/cupsd.conf.gz)

TO be noted it is the safe file used by the older version  of cups (2.2.1)

**Comment by michaelrsweet** [comment]
Also now have reports of this on macOS, investigating...

**Comment by frazhome** [comment]
at SUSE SLES 15 sp1 it is also broken.

Is there anything I could do to help you?

**Comment by DemiMarie** [comment]
`admin.cgi` seems to be trying to get a Kerberos ticket, but there is no way for it to do so: it doesn’t have permissions to access the host keytab, and since it runs as a system user it wasn’t granted a ticket during login.  Instead, it should connect over AF_UNIX, and cupsd should `admin.cgi` to be authenticated by virtue of running as the `lp` user.

**Comment by DemiMarie** [comment]
Debug logging reveals that `cupsd` is sending a `WWW-Authenticate: PeerCred` header, which probably should not happen.  This suggests that `cupsd` isn’t honoring `PeerCred` authentication when `DefaultAuth` is set to `Negotiate`.  It could also mean that the CGI programs are not sending an `SCM_CREDENTIALS` control message.

@michaelrsweet does that help?

**Comment by DemiMarie** [comment]
Problem seems to be that CGI programs

* Refuse to try PeerCred authentication:  <https://github.com/apple/cups/blob/ec8beb8952388a3ce650cc1477cd386546ed7318/cups/auth.c#L1047-L1069>
    Even if they tried, they would fail, as the `lp` user does not have enough privileges.
* Do not have Basic auth credentials they can use.
* Cannot obtain a Kerberos ticket.

There are two solutions:

1. Run the CGI programs with enough privileges that they can administer CUPS themselves.
2. Run them as a separate user, such as `cupscgi`.  Use sandboxing (`pledge` on OpenBSD, seccomp on Linux, seatbelt on macOS, etc) to prevent them from using `ptrace` or otherwise interfering with each other.  And link each CGI process to the request that made it.  This can be done using its PID, which is race-free so long as cupsd does a wait with `WNOWAIT`, then removes the child PID from its internal database, and finally actually reaps the child.

**Comment by DemiMarie** [comment]
One fix is to use S4U2Self when GSSAPI is in use.  That said, running the CGI programs as a separate user is still a good idea.

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.

**Comment by kenshin33** [comment]
can confirm. Built 2.3.3 with the patch from the pull request, it seems to work !
