### ISSUE TITLE
map ip address to hostname (job-originating-host-name)

### ISSUE THREAD

**Issue by GreatBahram** [apple/cups#5655]
Hello there,

I want to map clients' IP addresses to hostnames, in order to see the hostname in `job-originating-host-name`.

The things I have done so far to achieve this goal:

* Manually add computer names to `/etc/hosts` to see and this only works when I add `HostNameLookups On` to cups configuration file, though I read this directive is there to translate printer addresses to hostname, right?

* I also connect the server to a local DNS server to see if it has a positive effect or not, it was hopeless.

I was wonder how exactly cups translate IP addresses to hostnames and How can I see users' hostnames, for `job-originating-host-name`, whenever it is possible? Do you have any suggestions?

Thanks.

**Comment by michaelrsweet** [comment]
CUPS uses the value of the HostNameLookups setting to determine whether to perform a reverse lookup of the client's address. Local (domain socket and loopback interface) traffic is always tagged as "localhost".

You can do `cupsctl HostNameLookups=On` to enable hostname lookups for filling this value. But please understand that certain configurations (such as SSH tunnels, which we don't officially support, and other proxy technology) can lead to incorrect values being reported since we only record the address of the closest connection to the server.
