### ISSUE TITLE
ipp2ppd & printer icon?

### ISSUE THREAD

**Issue by apizz** [apple/cups#5673]
I'm not sure if this is pertinent to this project, but wanted to ask anyway ...

It recently became necessary to add a printer configured for AirPrint programmatically.  When added manually, it appears the resulting ppd file in `/etc/cups/ppd` is produced using the built-in `ipp2ppd` tool (`/System/Library/Printers/Libraries/ipp2ppd`).  This does not appear to be affiliated with CUPS directly, but I can't find this tool referenced as part of any linux distribution: only on Mac.

Interestingly, when `ipp2ppd` is run via Terminal as a regular user (ex. `ipp2ppd ipp://<printer_uri> everywhere`), the printer's icon is created in `/Library/Printers/Icons` as an .icns file named after the printer model.  This icon is also reflected in the resulting ppd file such that once added the printer's icon is shown in the Printers & Scanners preference pane.

However, when ipp2ppd is run as `root`, it does _not_ produce this icon and as a result, the final ppd file does not include this .icns file path and instead uses a generic printer icon.  Running a `diff` on the resulting ppd file created as a local user and as `root` reveals a single line of difference at line 19:

```
*APPrinterIconPath: "/Library/Printers/Icons/<printer model name>.icns"
```

Interestingly, looking at the traffic generated by `ipp2ppd` run as a regular user and as root, the available printer .png files on the printer are listed as part of the `printer-icons` information collected by the ipp `get-printer-attributes.test` and are subsequently requested and successfully retrieved.  My suspicion then is something about `ipp2ppd` being run as root prevents the OS from processing the .png files and turning them into a single .icns file.

Is this something that is or could be addressed by this project?

**Comment by michaelrsweet** [comment]
@apizz The ipp2ppd utility is *not* part of the CUPS project and isn't something we can help you get a fix (use <bugreport.apple.com> for that).

That said, ipp2ppd uses a user agent to generate the icon file in /Library/Printers/Icons, but that service is not accessible by root (since the root user does not have a login session, just the user you logged in as...) Since ipp2ppd is never run as root and is not supported as a user program, I doubt it will be "fixed" for this...

The publicly supported method for creating an AirPrint queue from the command-line is to use the lpadmin command with the `-m everywhere` option.

**Comment by gmuth** [comment]
When using the IPP-CUPS operation Create-Local-Printer (and making it permanent later), is it possible to configure the icon via IPP? On macOS a standard Icon is used, even when the IPP printer offers an icon.
