### ISSUE TITLE
cupsGetDests can not retrieve the default printer name from file ~/.cups/lpoptions under some case

### ISSUE THREAD

**Issue by tangyanli** [apple/cups#5684]
The #5683 is closed, so I create this new issue.
I have tested the newest branch master & 2.2.x. The test result is as below:

If the default printer name in the file /etc/cups/printers.conf is empty, then the phenomenon described in the #5683 has been fixed.

But if the default printer name in the file /etc/cups/printers.conf is not empty, then the phenomenon described in the #5683 is still existent.

**Comment by michaelrsweet** [comment]
Investigating; the order *should* be: environment variables (LPDEST and PRINTER) or location-based default (macOS), lpoptions default, then server default.

**Comment by michaelrsweet** [comment]
OK, I've reworked the defaults code a bit to make sure the order of precedence is honored. Note that on macOS the default printer is usually "last used printer" so we'll never use the lpoptions default at all (and it will get switched to the last used printer when you update the saved settings).

[master 34b446d86] Refactor the defaults code so that the correct order of precedence is respected in all cases (Issue #5683)

[branch-2.2 457d534a9] Refactor the defaults code so that the correct order of precedence is respected in all cases (Issue #5683)
