### ISSUE TITLE
Enhance scheduler to avoid duplicate DNS-SD service names

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5688]
Hi Mike,

I have a report for Centos/RHEL 7 https://bugzilla.redhat.com/show_bug.cgi?id=1549304 , but I looked into code in current upstream master  and the issue seems to be here as well (in scheduler/dirsvc.c).

User has two printers of the same model, both installed on the server, which is set to share the queues, so their dns-sd id for avahi is : 

Xerox ColorQube 8580DN @ <server>

info string is taken from the printer. Then avahi is unable to register the second print queue with:

W [26/Feb/2018:09:36:48 -0800] DNS-SD registration of "Xerox ColorQube 8580DN @ server" failed: Local name collision

The fix can be to add some other string into dns-sd id (e.g. print queue name) when info strings are the same, but I would like to know your opinion about how the issue can be properly solved and if it can be solved, which string should be added.

What do you think about it, Mike?

**Comment by michaelrsweet** [comment]
The DNS-SD service name comes from the printer description (printer-info attribute) and the local system name. The default description is the make and model when adding via the web interface or the printer name when adding via lpadmin, but can be changed at any time, including when you create the queue.

Right now we don't offer a way to directly change the DNS-SD service name directly, nor do we have code that checks for local collisions since mDNSResponder does that for us (and apparently Avahi does not...)

Since this is the first report of this problem we've gotten in the last 10+ years, I'm not convinced this is an urgent issue to resolve but I'll keep this in the pending queue of possible future enhancements.

**Comment by michaelrsweet** [comment]
Oh, and for RHEL the solution might be to put the queue name in the printer-info string when adding the printer via system-config-printer, e.g., "Example Laser Printer (example1)" and "Example Laser Printer (example2)".

**Comment by zdohnal** [comment]
> Oh, and for RHEL the solution might be to put the queue name in the printer-info string when adding the printer via system-config-printer, e.g., "Example Laser Printer (example1)" and "Example Laser Printer (example2)".

Yep, that's how user worked it around too, though it would be fine to have it done automatically.

> Right now we don't offer a way to directly change the DNS-SD service name directly, nor do we have code that checks for local collisions since mDNSResponder does that for us (and apparently Avahi does not...)
> 

I can check with our Avahi maintainers if they are willing to do something about it so we could avoid changes in CUPS, especially only for Avahi...

> Since this is the first report of this problem we've gotten in the last 10+ years, I'm not convinced this is an urgent issue to resolve but I'll keep this in the pending queue of possible future enhancements.

No prob, I just asked because I will create patch and propose it to you as pull request, so I wanted to know what solution of those duplicates you would prefer (probably print queue name as you suggested in next comment).

Thank you!

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.
