### ISSUE TITLE
cupsd doesn't start automatically after reboot when service is enabled 

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5708]
Hi Mike,

we encountered the issue with cupsd service unit file and systemd in Fedora/RHEL- if cupsd is installed and service unit file is enabled, but it is not started manually, then cupsd is not started after reboot, which should be.
The reason is the printer.target in WantedBy directive is disabled and not used in Fedora/RHEL and setting it to f.e. default.target does the trick.

Is something amiss in systemd configuration files or should cupsd service unit use different target?

Thank you for looking into it!

**Comment by rmetrich** [comment]
Hello,
Adding some complementary information.
I understand the `cups.service` unit is designed to be executed on-demand, based on either `cups.path` (`/var/cache/cups/org.cups.cupsd`) or `cups.socket` (unix socket).

Initially, just after installing, there is no `/var/cache/cups` and no socket connection, so the service doesn't start.
Then, upon a user login in, `/usr/libexec/gsd-print-notifications` starts, causing an incoming connection on the socket, causing `cups.service` to execute.
`cups.service` creates `/var/cache/cups/org.cups.cupsd` and runs.

At next reboot, since `/var/cache/cups/org.cups.cupsd` now exists, `cups.path` activates `cups.service` and everything now rocks.

So my question: why having a so complicated mechanism, shouldn't `cups.service` have just some `[Install]` directive to start immediately at boot:

~~~
[Install]
WantedBy=default.target
~~~

We can then get rid off `cups.path`.
I would still keep `cups.socket` enabled so that if the distro doesn't enable `cups.service` at boot and some connection gets in, `cups.service` gets executed anyway.
Still, there is then an issue with the `ListenAddress` for `cups.socket` (currently Unix socket, should also be `[::1]:631` or even maybe (depending on administrator's configuration `[::]:631`.

**Comment by zdohnal** [comment]
> Then, upon a user login in, `/usr/libexec/gsd-print-notifications` starts, causing an incoming connection on the socket, causing `cups.service` to execute.
> `cups.service` creates `/var/cache/cups/org.cups.cupsd` and runs.

Just note which Renaud did not mention - this happens only on machine with GUI (GNOME in this case). User needs to start cups service manually on the machine without GUI (typically servers).

> We can then get rid off `cups.path`.

IIUC cups.path is still useful for client machines, which do not depend web interface and have Browsing disabled (Browsing is On in Fedora/RHEL) - if cups.path would miss, then some jobs, which weren't finished before shutdown, wouldn't have been printed after reboot.

**Comment by michaelrsweet** [comment]
@zdohnal As we do not package CUPS on Linux or use systemd on any Apple operating systems, I cannot say whether the WantedBy target should/can be changed in general. I would suggest contacting (at least) Till Kamppeter off-line to discuss things, and then let us know what the default systemd files should say to minimize patching.

@rmetrich The reason for the complicated life cycle is that cupsd serves many purposes, and since there is a strong desire to minimize the number of running daemons on desktop systems (at least) we need to handle both run-on-demand and run-always modes.

**Comment by zdohnal** [comment]
@michaelrsweet Sent email to Till today.

**Comment by zdohnal** [comment]
The printer.target makes cups.service to start when a printer device is detected, so it makes sense to be defined in org.cups.cupsd.service - so it is started only when a such device appears and adding multi-user.target would cause to cupsd being run everytime when it is enabled.
I was thinking of new systemd unit - let's say org.cups.cupsd-server.service unit - which would conflict with other cups systemd units and can be used primary for print servers.

What do you think about? I'll post the idea on cups-devel mailing list.

**Comment by jsmeix** [comment]
A general side note regarding
"makes cups.service to start when a printer device is detected"
i.e. starting cupsd when "a printer device is detected":

In general it might be perceived as a security violation
(in particular on business systems, both servers and workstations)
when daemons that run as root get automatically started all of a sudden
only because something that looks like or pretends to be
"a printer device" is somehow detected.

**Comment by michaelrsweet** [comment]
I think this has been addressed in OpenPrinting CUPS. If not, let's move this to there...
