### ISSUE TITLE
lp -o raw behavior 

### ISSUE THREAD

**Issue by chiamwuixiang** [apple/cups#5714]
Thank you for your replied @michaelrsweet on https://github.com/apple/cups/issues/5711#issue-543814400.

But I am very curious on this behavior, 

1) When I use windows driver to print a test page with inverted orientation and print ZPL template with -o raw command afterwards, the label print out orientation was following the window set orientation correctly. 

2) However when i tried print a test page using CUPS with inverted orientation (orientation-requested=6 setup with lpadmin on the printer) and print with lp -o raw command afterwards, the printed template orientation does not follow the CUPS test page orientation.

If "raw" option just send the data to the printer without going through any filter, it should be following the latest printer orientation settings right? But in this case, it follows the windows orientation settings but not following the CUPS orientation settings.

Is there any files in CUPS that we can adjust default orientation of CUPS to change it from default 3 to 6 or something?

Sorry for the trouble and thanks for your help.

**Comment by michaelrsweet** [comment]
Again, "-oraw" means "send this file *without processing or interference*". That has always been the case and will not be changed.

The Windows driver sets the orientation. The CUPS driver sets the orientation. But if the raw file does not set the orientation then it will generally be the default one (since most printers reset their state between jobs/connections).

As long as you are doing raw printing, there is absolutely nothing that CUPS can do to "fix" your issue.
