### ISSUE TITLE
CUPS queue hangs when network printer is unreachable.

### ISSUE THREAD

**Issue by AveekBasu** [apple/cups#5752]
In a client server environment, CUPS queue hangs when the network printer is unreachable.

Environment:
Server: Running CUPS 1.4.2 \ 1.6.3 \ 2.2.7
Client: Running CUPS 1.4.2 \ 1.6.3 \ 2.2.7

This is an environment where the system prints numerous documents a day without any issue.
It has been found that if the printer becomes unreachable due to a NW failure (if there are multiple link losses in a short period of time say 3-4 times in a minute) or frequent power outages, the queue hangs and stops printing. One thing to note is, we are talking about multiple frequent link losses and not a single link loss. Which means that the printer is becoming unreachable multiple times.
[CUPS_Error_Logs.zip](https://github.com/apple/cups/files/4292588/CUPS_Error_Logs.zip)

Attached are the CUPS logs from the server and the client for reference.

Say for example there were couple of jobs which were fired continuously and there were no issues till Job # 177 however during the time Job # 178 was about to be printed, there were multiple link failures in a short span of time. It is observed that the Job # 178 seems to have fallen into an infinite loop, but nothing shows why this happens, no errors or so. Job # 178 and following are all waiting in the queue because 178 does not finish.

The only way to recover at this point is to restart the CUPS in the server or enable the client queue (however just enabling the queue does not always work).

There was exactly a similar issue (https://bugzilla.redhat.com/show_bug.cgi?id=124345) which was reported a long time back in CUPS 1.1.17. The issue seems to be almost similar and is reprocudible in the latest version of CUPS as well.

Regards,
Aveek

**Comment by jsmeix** [comment]
@AveekBasu 
because you wrote
```
... the Job # 178 seems to have fallen into an infinite loop,
but nothing shows why this happens, no errors or so
```
as a side note FYI see
https://github.com/apple/cups/issues/5559

Aditional info regarding how to debug such issues:
Because in
https://github.com/apple/cups/issues/5559
it took us (i.e. the SUSE support engineers) almost endlessly
to get a useful matching CUPS debug log excerpt
of such a sporadic happpening failure
I developed a generic CUPS wrapper backend "monitor"
that runs in parallel with the actual backend to monitor it, see
https://github.com/jsmeix/cups-backends

Perhaps that might be useful also for you to get actually
meaningful debug info when such rare issues happen.

**Comment by AveekBasu** [comment]
@jsmeix  Thanks...I will try it out.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
