### ISSUE TITLE
CUPS issue

### ISSUE THREAD

**Issue by walk5** [apple/cups#5771]
I hope you can help and I am in the right place. I am running CUPS with Kubuntu 19.10. It comes installed. It found my Epson WF-2650 printer but this printer is not in the list. I had it working right and something happened and it stopped sending prints to the printer.Now it sends prints but it spits out blank pages then prints a little bit of code on a few more pages then more black pages then I am not sure because I cancel the print. 

Please help. I found this printer is working and compatibile with CUPS but I am not sure what I am doing wrong. 

I am still fairly new to linux and learning. I asked in another place but I was not able to fix it.

**Comment by zdohnal** [comment]
Hi,

The first rule of thumb would be to name the issue with more specific name than 'CUPS issue' - like e.g. '<your printer model> spits out garbage'.

> It comes installed. It found my Epson WF-2650 printer but this printer is not in the list. 

Would you mind explaining what comes installed and where? I'm not quite sure how to understand the sentences. Do you have two devices? What do you mean by 'the list' and what found your Epson?

The reason why I'm asking like this (assuming your printer is in your local nework):
- the new (network printer released since 2010+, usb printer released around 2016+) printer doesn't need to be installed by you to printing correctly - CUPS has temporary queues feature, which makes a queue appear during print dialog (e.g. in libreoffice) and disappear after printing
- or when you have cups-browsed service running, it creates permanent (doesn't disappear after printing) queue from temporary queue
- but still you can install your printer manually via several interfaces (your desktop 'Settings', CUPS web/CLI interface, system-config-printer) and install it with two specific models - 'everywhere' model (driverless model) or specific printer model, if available (deprecated).

So what of those applies for your case? :)  

> Now it sends prints but it spits out blank pages then prints a little bit of code on a few more pages then more black pages then I am not sure because I cancel the print.

IMO it sounds like a filter/internal interpreter issue to me, but an other rule of thumb - when you reports an issue, it is more than welcome to attach files with logs (github accepts any files with .txt suffix as attachment - so just rename the log to add .txt suffix and click on 'pasting' under comment window).
There are several manuals about how to collect logs, so I would advertise Fedora one :) https://fedoraproject.org/wiki/How_to_debug_printing_problems#How_to_get_and_attach_logs_for_bug_report

I need to mention I'm not able to merge any possible fix for CUPS if needed, I'm just collecting debugging info for @salgernon which has the power :) .

**Comment by walk5** [comment]
I am sorry about not giving very good info. I am newer to this an still trying to get it right. Add frustration too and with that you end up with a basket case. Thats me right now. CUPS is only one Linux issues I am having right now. Slowly working through it. Did I mention slowly? Very Slowly most of the time.

I am Using Kubuntu 19.10. CUPS 2.2.12 is what was "installed". I am not sure if installed is the right word. So when I go to the internet and type localhost:631, that is the version of CUPS that is available for me to use. 

I clicked on add a printer. My Epson WF-2650 was plugged in via usb. My printer was in the local printers available. Then I continued the process to where you add the model. My model is not in that list but when I google searched my model it said it was compatible. I have tried other WF Epson printer models to make a connection. I had it working before but it stopped communicating for some unknown reason. Now no matter what printer model I try, it does not work properly. I get blank pages then some pages with triangles stars and things like that then more blank and so on until I cancel. Not all of the models will even do that. Some will tell me printing then just sit in the queue until I delete it.

I hope to not offend in any away but I truely dislike Windows and I am trying to get as far away from it as possible but I love this printer.

**Comment by zdohnal** [comment]
> I am sorry about not giving very good info. I am newer to this an still trying to get it right. Add frustration too and with that you end up with a basket case. Thats me right now. CUPS is only one Linux issues I am having right now. Slowly working through it. Did I mention slowly? Very Slowly most of the time.
>
I understand your frustration - the previous comment was written as explanation what to do. Still the generic summary gives no value for a developer.
 
> I am Using Kubuntu 19.10. CUPS 2.2.12 is what was "installed". 

Good job! CUPS version is good info to know.

> I clicked on add a printer. My Epson WF-2650 was plugged in via usb. My printer was in the local printers available. Then I continued the process to where you add the model. My model is not in that list but when I google searched my model it said it was compatible. I have tried other WF Epson printer models to make a connection. I had it working before but it stopped communicating for some unknown reason. Now no matter what printer model I try, it does not work properly. I get blank pages then some pages with triangles stars and things like that then more blank and so on until I cancel. Not all of the models will even do that. Some will tell me printing then just sit in the queue until I delete it.
> 
Ok, so you installed the print queue via CUPS web interface and with a specific printer driver. But there's not much to tell without logs - I guess I didn't say it explicitly - would you mind attaching the job log of print job (that's the object which is created when you send something to print) as a file here? You can follow the link in previous comment.

Since you use USB printer, you can check if it supports IPP-over-USB and try to use ippusbxd instead of specific driver. See https://wiki.debian.org/CUPSDriverlessPrinting#IPP-over-USB_.28Short_Version.29

**Comment by debiantriage** [comment]
Hello walk5,

You would be doing yourself a very big favour by putting the WF-2650 on the network with a WiFi connection. zdohnal has hinting at doing this in his second post. The front panel of the WF-2650 should help you set up a connection.

When you have done that, run these two commands in a terminal:

`avahi-browse -rt _ipp._tcp > log1.txt`
`avahi-browse -rt _uscan._tcp > log2.txt`

You can view these logs with _less_ or any text editor. We also need to see their contents, so please send them here as attachments.

Personally, I am not inclined to tackle this issue if you keep the WF-2650 attached by USB or insist on using the Epson printer drivers. Both give me more work to do!

Regards,

Brian.

**Comment by jschwender** [comment]
This printer is a ESC/P-R printer, which needs a special filter available from epson. 
see  [http://www.openprinting.org/printer/Epson/Epson-WF-2650_Series](url)
Check if it is installed by running `dpkg -l printer-driver-escpr` in a terminal. I doubt that this one works without Epson driver.
