### ISSUE TITLE
Where to start troubleshooting?

### ISSUE THREAD

**Issue by github-pba** [apple/cups#5848]
Hi everybody!

I encounter problems printing on my Sony UP-DR200 thermosublimation photo printer, and I have trouble understanding wether CUPS, Gutenprint or libusb might be the culprit. 

> Note: I _hate_ printing on Unix systems since 1986 and avoided it whenever possible. Now it comes back to me and hits me hard!

The final goal is to offer this printer to a Win10 system, because there are no Win10 drivers for this printer. W10 -> Postscript -> CUPS/Gutenprint -> Printer -> Paper

Environment: 
- Debian Linux 10.6 + up-to-date patches
- CUPS v2.2.10
- Linux Gutenprint v5.3.1

I have configured the printer, and as soon as I start printing the test page, communication is established but fails with the error 
```
Failure to send data to printer (libusb error -1: (65536/131071 to 0x01))
```

Can somebody be so kind to give me a hint where it's best to start troubleshooting? I suspect Gutenprint ...

Here is the part from the error log I think which help you, and as an attachment, the entire error log in Debug mode

[error_log.zip](https://github.com/apple/cups/files/5479852/error_log.zip)
```
[...]
I [01/Nov/2020:20:06:55 +0100] [Job 3] Started backend /usr/lib/cups/backend/gutenprint53+usb (PID 770)
D [01/Nov/2020:20:06:55 +0100] [Job 3] Multi-Call Dye-sublimation CUPS Backend version 0.88G
D [01/Nov/2020:20:06:55 +0100] [Job 3] Copyright 2007-2018 Solomon Peachy
D [01/Nov/2020:20:06:55 +0100] [Job 3] This free software comes with ABSOLUTELY NO WARRANTY!
D [01/Nov/2020:20:06:55 +0100] [Job 3] Licensed under the GNU GPL.  Run with \'-G\' for more details.
D [01/Nov/2020:20:06:55 +0100] [Job 3] STATE: +org.gutenprint-searching-for-device
D [01/Nov/2020:20:06:55 +0100] [Job 3] Probing VID: 054C PID: 035f
D [01/Nov/2020:20:06:55 +0100] [Job 3] STATE: +connecting-to-device
D [01/Nov/2020:20:06:55 +0100] [Job 3] OUTFORMAT=\"(null)\", so output format will be CUPS/PWG Raster
D [01/Nov/2020:20:06:55 +0100] [Job 3] STATE: -connecting-to-device
D [01/Nov/2020:20:06:55 +0100] [Job 3] STATE: -org.gutenprint-searching-for-device
D [01/Nov/2020:20:06:55 +0100] [Job 3] Initializing \'Sony UP-DR150/UP-DR200/UP-CR10\' backend (version 0.26)
D [01/Nov/2020:20:06:55 +0100] [Job 3] Printing started (1 copies)
[...]
D [01/Nov/2020:20:06:57 +0100] [Job 3] Printing page 1, 97%
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Printing page 1, 97%", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: job-media-progress=97
D [01/Nov/2020:20:06:57 +0100] [Job 3] Printing page 1, 98%
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Printing page 1, 98%", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: job-media-progress=98
D [01/Nov/2020:20:06:57 +0100] [Job 3] Printing page 1, 99%
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Printing page 1, 99%", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: job-media-progress=99
D [01/Nov/2020:20:06:57 +0100] [Job 3] Processing page 2...
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Processing page 2...", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] Rendering completed
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Rendering completed", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] Printing page 1, 100%
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Printing page 1, 100%", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: job-media-progress=100
D [01/Nov/2020:20:06:57 +0100] [Job 3] PID 768 (/usr/lib/cups/filter/gstoraster) exited with no errors.
D [01/Nov/2020:20:06:57 +0100] [Job 3] Finished page 1...
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Finished page 1...", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] Gutenprint: ================ Done printing page 1 ================
D [01/Nov/2020:20:06:57 +0100] [Job 3] Gutenprint: Ending job
D [01/Nov/2020:20:06:57 +0100] [Job 3] Gutenprint: stats 16736475B, 0.010u, 0.460s, 1.997el
D [01/Nov/2020:20:06:57 +0100] [Job 3] Gutenprint: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
D [01/Nov/2020:20:06:57 +0100] [Job 3] Gutenprint: ============================================================
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-colors=#00FFFF#FF00FF#FFFF00
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-high-levels=100
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-low-levels=10
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-names=\'\"Unknown\"\'
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-types=ribbonWax
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-levels=-2
D [01/Nov/2020:20:06:57 +0100] [Job 3] ATTR: marker-message=\'\"Unknown remaining prints on Unknown media\"\'
D [01/Nov/2020:20:06:57 +0100] [Job 3] Printing page 1
D [01/Nov/2020:20:06:57 +0100] [Job 3] Set job-printer-state-message to "Printing page 1", current level=INFO
D [01/Nov/2020:20:06:57 +0100] [Job 3] PID 769 (/usr/lib/cups/filter/rastertogutenprint.5.3) exited with no errors.
E [01/Nov/2020:20:07:03 +0100] [Job 3] Failure to send data to printer (libusb error -1: (65536/131071 to 0x01))
D [01/Nov/2020:20:07:03 +0100] [Job 3] Set job-printer-state-message to "Failure to send data to printer (libusb error -1: (65536/131071 to 0x01))", current level=ERROR
D [01/Nov/2020:20:07:04 +0100] [Job 3] PID 770 (/usr/lib/cups/backend/gutenprint53+usb) stopped with status 1.
I [01/Nov/2020:20:07:04 +0100] [Job 3] Backend returned status 1 (failed)
I [01/Nov/2020:20:07:04 +0100] [Job 3] Job held for 300 seconds since it could not be sent.
```

Thank you very much!

**Comment by jsmeix** [comment]
Hello

On 2020-11-03 07:56, github-pba wrote:
> I encounter problems printing on my Sony UP-DR200 thermosublimation
> photo printer, and I have trouble understanding wether CUPS,
> Gutenprint or libusb might be the culprit.
...
> E [01/Nov/2020:20:07:03 +0100] [Job 3] Failure to send data to printer
> (libusb error -1: (65536/131071 to 0x01))
> D [01/Nov/2020:20:07:03 +0100] [Job 3] Set job-printer-state-message
> to "Failure to send data to printer (libusb error -1: (65536/131071 to
> 0x01))", current level=ERROR
> D [01/Nov/2020:20:07:04 +0100] [Job 3] PID 770
> (/usr/lib/cups/backend/gutenprint53+usb) stopped with status 1.
> I [01/Nov/2020:20:07:04 +0100] [Job 3] Backend returned status 1 
> (failed)

it is /usr/lib/cups/backend/gutenprint53+usb that failed with
"Failure to send data to printer (libusb error -1: (65536/131071 to 
0x01))"
and /usr/lib/cups/backend/gutenprint53+usb belongs to Gutenprint
http://gimp-print.sourceforge.net/

On
http://gimp-print.sourceforge.net/p_Supported_Printers.php
the Sony UP-DR200 is listed as supported
but that this device requires a special backend
/usr/lib/cups/backend/gutenprint53+usb
instead of the generic CUPS backend for normal USB printers
/usr/lib/cups/backend/usb
(blacklisted in /usr/share/cups/usb/net.sf.gimp-print.usb-quirks)
indicates that this device does not behave
like a normal USB printer should do
so it seems this device needs special USB handling
which indicates that USB issues are more likely
with this device.


Kind Regards
Johannes Meixner
-- 
SUSE Software Solutions Germany GmbH
Maxfeldstr. 5 - 90409 Nuernberg - Germany
(HRB 36809, AG Nuernberg) GF: Felix Imendoerffer

**Comment by github-pba** [comment]
Thank you very much, Johannes. 

And a special thank you for your clear and reproducible analysis. This greatly helps, and I will get in touch with the Gutenprint developers or start looking at Gutenprint's source code.

**Comment by jsmeix** [comment]
@github-pba 
you are welcome.

Perhaps you have another more "normal" USB printer
that you could use to verify if there are generic USB communication issues
on the system where a USB printer should be connected to
or if USB communication issues only appear with the Sony UP-DR200.

For what I have in mind about possible generic USB communication issues
cf. the section "USB" in https://en.opensuse.org/SDB:Configuring_Scanners
and therein in particular see the paragraph about
`Weird issues may happen when the USB 3 kernel driver xhci_hcd is used`.
So perhaps similar kind of problems may also appear with special kind of
USB printing devices that do not behave as USB printers usually do?

Furthermore the generic CUPS backend /usr/lib/cups/backend/usb
has special "quirks" support implemented for special cases of USB printers
(because some "normal" USB printers behave somewhat special sometimes)
see /usr/share/cups/usb/org.cups.usb-quirks (on my openSUSE Leap 15.1 system
which could be located in another directory on other Linux systems).
I guess the special backend /usr/lib/cups/backend/gutenprint53+usb
may perhaps not have such special "quirks" support implemented?

But I am not at all a USB expert so I cannot help with actual debugging
of specific USB communication issues.

**Comment by RobertKrawitz** [comment]
We have the bug report at Gutenprint.

**Comment by github-pba** [comment]
Thank you, Robert.

Gutenprint works better, but not without any problem, in Version 5.3.3. At least single page printing works, and then the unix print queue needs to be restarted.

For a cross reference, I work with them using this ticket: https://sourceforge.net/p/gimp-print/support-requests/585/
