### ISSUE TITLE
Detects the same printer multiple times, likes to ignore driver and send PDF, huge waste of paper

### ISSUE THREAD

**Issue by realh** [apple/cups#5851]
I have a Samsung ML-2950 which supports ipp but not Airprint; it uses PCL. CUPS seems to detect it multiple times. For example, here are the options if I choose Modify Printer in CUPS on http://localhost:631:
![TooManyPrinters](https://user-images.githubusercontent.com/8783151/99718925-8d160b00-2aa3-11eb-83f6-cb1c43f24793.png)

I only have the one printer.

I don't get offered so many copies in GNOME settings or applications that can print, but there's usually more than one. AIUI this is handled by CUPS libraries which gnome-settings and other applications are linked with. The trouble is, the auto-detected ones often show up as driverless, so if I print to one by mistake it sends PDF to the printer, which appears as a few lines of garbage before it encounters a byte which it interprets as form feed, so it ruins several sheets of paper very quickly if I'm not at the printer ready to pull the plug. Reconfiguring it to use the correct driver only works temporarily, I just get another bogus entry turning up next time.

Can't CUPS do a better job of working out that this is always the same printer, eg by checking its MAC address, and make sure it remembers which driver I want to use with it?

**Comment by michaelrsweet** [comment]
First, it isn't always possible to get the MAC address of a printer without connecting to it, which will wake it. Try doing that on a network with 1000 printers!

Second, it looks like you may have extra backends that are discovering the same printer with different protocols, making it impossible for CUPS to (reliably) know that they are the same printer, or even which backend should be used in a given circumstance - for example, HPLIP includes a backend that is optimized for use with their drivers. When you just have the stock CUPS configuration this doesn't happen because we've integrated the discover of all standard protocols to avoid this.

Anyways, there isn't anything we've come up with to resolve this issue, but you can limit the number of duplicates by removing print drivers you don't need...

**Comment by realh** [comment]
The only thing that seems like I can remove is foomatic-db-engine. I've done that and restarted CUPS, but CUPS still offers multiple copies of this printer when it's switched on. It even seems that once I choose one and configure it, CUPS no longer recognises it as the same detected printer, because it presents the same one as a "new" printer.

There's also a difference between Modify Printer and Add Printer:

![ModifyPrinter](https://user-images.githubusercontent.com/8783151/110948733-9d474400-8339-11eb-980f-dfc6d3a0b543.jpg)
![AddPrinter](https://user-images.githubusercontent.com/8783151/110948756-a33d2500-8339-11eb-9c6f-cc86db4c7ea9.jpg)

Why the discrepancy? Perhaps the printer offers multiple protocols that have support built into CUPS? I need some way to filter out the protocols I don't want to use, but how?

**Comment by michaelrsweet** [comment]
The "driverless" one is cups-browsed.

The "beh" backend might also be doing discovery, not sure.

You can also check whether your distro has enabled SNMP lookups by default in the /etc/cups/snmp.conf file.

**Comment by realh** [comment]
FWIW I'm using Arch Linux, but I'm pretty sure I used to have the same problem in Debian. cups-browsed isn't running, it's masked/disabled in systemctl. AFAICT I should disable SNMP, which can be done by setting `Address 127.0.0.1` and/or removing the `Community` name in /etc/cups/snmp.conf. Is that right?

**Comment by michaelrsweet** [comment]
@realh Just comment the "Address" like out in snmp.conf.
