### ISSUE TITLE
[Feature Request] Allow attach multible connection possibility to one Printer

### ISSUE THREAD

**Issue by Mannshoch** [apple/cups#5855]
Most Printer allow to connect them on multiple ways.

This is the list which appear If I open "Avahi Zeroconf Browser"
![grafik](https://user-images.githubusercontent.com/7795891/100582918-449fee00-32ea-11eb-8404-d7754e334912.png)
All these printers in the List are the same device

- [ ] If you attach a new Printer, auto attach all connection possibility to this new Printer and try to set up a working connection on all of them. 
- [ ] May allow to manually to attach a connection to a Printer (e.g USB which is currently not connected while setup the printer)
- [ ] concatenate all information and features of these connections into one printer.
- [ ] on every printing CUPS use the best available path to connect a printer for a printing job.
- [ ] If needed CUPS collect status Information from different connection and try to find non or wrong working connection.

**Comment by michaelrsweet** [comment]
This really wouldn't help improve printing. First, because each protocol has different capabilities and might need a different driver, and second because all of those protocols you see are not printing protocols.

There is already a mechanism for choosing the preferred (standard) printing protocol for a printer that is supported by CUPS and can be configured via most printer web consoles. The Google Cloud Print protocols are *not* supported (and GCP has been discontinue by Google anyways), and the scanner protocols likewise have their own mechanism for picking the preferred protocol.

**Comment by michaelrsweet** [comment]
@Mannshoch It doesn't work that way.

WRT protocols, while it is not uncommon for a printer to support multiple network protocols (IPP, IPPS, LPD, raw socket, etc.), what *is* uncommon is for those to represent different network connections or paths. Having a different URI depending on whether you are at work or home, or whether you are connected to a VPN, or any number of other possibilities is just not something that CUPS is designed for. The closest we've come is to support an alternate domain name for DNS-SD service instance names (for the dnssd backend/URI scheme) so that CUPS can resolve the correct hostname and IP address depending on which subnet you are on in an organization. There *is* some work being done in the Printer Working Group to investigate possible solutions for what we are calling "IPP Direct", where a printer can advertise its local and remote/cloud/whatever endpoints. This would allow for the kinds of things you want, but at this point we are just tossing ideas around and haven't even gotten to the white paper stage of a proposal. There are serious security and usability issues that need to be figured out before we'll have something that can be specified and implemented...

Different drivers can have vastly different capabilities. Some may be specific to your printer, others might be generic for the class of device or supported file formats. The fact that you have multiple instances of the same driver probably means that there is a problem with the packaging of the driver or an issue specific to your system - your Linux distributor may be able to help with that...
