### ISSUE TITLE
How to judge whether the printer type is local or network

### ISSUE THREAD

**Issue by dreamtale90** [apple/cups#5861]
I have tried this method. 
First, I added the same printer through USB and network cable respectively. 
Then query the device through the cupsGetDests API. The value of the "printer-type" field of both printers is 0x80901c. 
According to the definition of cups_ptype_e, I understand that there should be CUPS_PRINTER_LOCAL and CUPS_PRINTER_REMOTE type. But now it's all local printers. Why is that?
```
enum cups_ptype_e			/* Printer type/capability bit
					 * constants */
{					/* Not a typedef'd enum so we can OR */
  CUPS_PRINTER_LOCAL = 0x0000,		/* Local printer or class */
  CUPS_PRINTER_CLASS = 0x0001,		/* Printer class */
  CUPS_PRINTER_REMOTE = 0x0002,		/* Remote printer or class */
  CUPS_PRINTER_BW = 0x0004,		/* Can do B&W printing */
  ........
};
```

**Comment by michaelrsweet** [comment]
The remote type is for remotely-hosted printers, i.e. printers hosted and shared by another CUPS server. A network printer is locally-hosted and has all processing (filtering, drivers, etc.) done on the local machine.

Right now the best way to detect whether a printer is locally connected or on the network is to look at the "device-uri" value, although for some URI schemes Linux (ipp, hplip, gutenprint) it isn't always obvious since they can refer to both local (IPP-USB in the case of the ipp scheme, regular USB for hplip and gutenprint) and network connections.
