### ISSUE TITLE
GPL Ghostscript 9.53.3: Unrecoverable error, exit code 1

### ISSUE THREAD

**Issue by Germano0** [apple/cups#5865]
SUMMARY
I have a particular PDF document that triggers a CUPS Ghostscript error. Since the PDF viewer I use is KDE Okular, I first [reported the issue there](https://bugs.kde.org/show_bug.cgi?id=430118) but I have been told that is not an Okular problem.
Since I cannot publish the PDF here, I will send it by e-mail to any of the Okular developers that need it.
I attach CUPS debuginfos that I got by using "LogLevel debug" in /etc/cups/cupsd.conf

STEPS TO REPRODUCE
1. In KDE Okular open the document, press CTRl + P to print
2. Open Options button, select "Pages" and write 544 (or any other number)
3. Click Print button

OBSERVED RESULT
Nothing happens, document stuck in CUPS print queue

EXPECTED RESULT
Print the page

SOFTWARE/OS VERSIONS
cups 2.3.3
poppler 0.90.0
Okular 20.08.3
KDE Frameworks 5.76.0
Qt 5.15.1
Fedora 33

[cups_errors.txt](https://github.com/apple/cups/files/5659002/cups_errors.txt)

**Comment by zdohnal** [comment]
Hi,

the error happens in ```gstoraster``` filter from ```cups-filters``` project, which uses ```ghostscript```. The produced error message is from ghostscript.
You can either report this to [cups-filters](https://github.com/OpenPrinting/cups-filters) or to [Fedora bugzilla](www.bugzilla.redhat.com), but in both cases please upload the file you tried to print too.

**Comment by Germano0** [comment]
>  but in both cases please upload the file you tried to print too.

I will send it by e-mail to who will required it. I need an e-mail address

**Comment by Germano0** [comment]
https://github.com/OpenPrinting/cups-filters/issues/329

**Comment by zdohnal** [comment]
> > but in both cases please upload the file you tried to print too.
> 
> I will send it by e-mail to who will required it. I need an e-mail address

I guess the file is confidential - can you reproduce the issue with non-confidential file?
Otherwise you have several options:

1. send your file to cups-filters maintainer and agree with him sending the modified file to ghostscript upstream
2. send your file to ghostscript upstream and hope it will trigger the error unfiltered
3. send your file to ghostscript upstream and hope they will be able to rerun your filter chain, giving  them the file which goes to `gs` and triggers the issue for sure
4. apply filters on your file by yourself (see ```man cupsfilter``` and your cups log), get the file which goes to ```gstoraster``` filter, and send this file to ghostscript upstream

All of those options will need more actions from you or you'll need to agree with the fact the file will be shared with at least 2 people.

**Comment by Germano0** [comment]
> I guess the file is confidential

Not confidential. Can you send me your e-mail address at $myname.$mysurname@gmail.com so I can send it to you?

**Comment by zdohnal** [comment]
If it is not confidential, please report the issue on bugzilla.redhat.com and attach the file there. I'm CUPS+cups-filters maintainer for Fedora.
If the file is too big, try to print only part of it and check if it still fails. If it does, take the file from /var/spool/cups (with the highest number) and attach that file to the ticket.

**Comment by Germano0** [comment]
> Not confidential. Can you send me your e-mail address at `$myname.$mysurname@gmail.com` so I can send it to you?

I don't know why I wrote that the file is *not* confidential, because actually it is confidential.
By the way I have talk to @zdohnal via e-mail and he did not manage to reproduce the problem, but I still can manage to reproduce it
