### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Emiliop89** [apple/cups#5882]
Hi! I started printing whit CL-S621 of Citizen, it's a printer for labels, .
I use Raspberry and i work in Jupyter.
I created an image whit Pillow, so i can use a lot of modes (1-bit pixels, black and white, stored with one pixel per byte, 8-bit pixels, black and white, 8-bit pixels, mapped to any other mode using a color palette, etc) but all of them made not good when i print.
I read that CUPS need a file in 1-bit mode to make a good image in printing and there isn't a way to set dithering, it's correct? There is any other library to print a good text label? thanks

**Comment by michaelrsweet** [comment]
Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance. While this printer isn't officially supported, the ZPL driver should work well with it. The bitmap imaging issues on low-resolution label printers are typically caused by the low resolution (203dpi) and antialiasing effects that tend to thicken lines and text.
