### ISSUE TITLE
usb backend fails, reports 'Failed to detach "usblp" module from NNNN:NNNN'

### ISSUE THREAD

**Issue by bitwombat** [apple/cups#5908]
While debugging why my USB-connected printer wasn't being seen by CUPS on Ubuntu 20.04, I ended up running `/usr/lib/cups/backend/usb` and, thankfully, debug output is produced (very much yay!):

```
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 95 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=11
DEBUG: Failed to detach "usblp" module from 04f9:00a2
```

This happens on `HEAD/b27a49b8a` as well.

The `usblp` module is _not_ loaded. I've `rmmod`'ed it and also blacklisted and rebooted. Same results.

No CUPS errors in `error_log`

Printer is a Brother HL-L2375DW

I'm compiling locally, so if you want me to sprinkle any `printf`'s around to help debug, let me know.

Note: After I hacked `backend/usb-libusb.c` to get rid of the module removing code, everything works.

**Comment by michaelrsweet** [comment]
@bitwombat OK, so this definitely is useful information!

The way that the USB printer class is defined, printers can provide a primary protocol and an alternate protocol for each set of endpoints, where protocol 1 and 2 are unidirectional and bidirectional "raw" protocols, 3 is IEEE 1284.4, and 4 is IPP-USB. In most printers only one protocol can be active at any time due to hardware limitations, so when ippusbxd finds an IPP-USB printer it immediately claims the printer's endpoints. Since most printers do not support simultaneous USB legacy and IPP-USB, that prevents you from using the legacy USB endpoints for printing...

Now, since your Brother printer supports IPP-USB (and AirPrint), you don't need to use the Brother driver at all but can just use the IPP Everywhere driver with ippusbxd. Or you could use the Brother driver with ippusbxd. Or you could remove ippusbxd (like you did) and use the Brother driver.

So what we'll be doing (over in OpenPrinting CUPS) is to update the USB backend to show a better error and/or exclude printers when IPP-USB is supported and ippusbxd is present.

**Comment by michaelrsweet** [comment]
Will track the fix for this in the [OpenPrinting bug](https://github.com/OpenPrinting/cups/issues/169) I just created.

**Comment by bitwombat** [comment]
Thanks for all thosedetails @michaelrsweet. I now understand a lot more about CUPS and printers. 

Please note that CUPS did *not* pick up the printer when ippusbxd was in operation... that's the whole reason I had to get down to this level of detail. Can create a different bug if this is of interest (no idea if it's uppusbxd's problem or CUPS').

**Comment by michaelrsweet** [comment]
@bitwombat Please do file a bug, but against [cups-filters](https://github.com/OpenPrinting/cups-filters) which is the component that is responsible for IPP-USB support on Linux.
