### ISSUE TITLE
There should be an option to customize org.cups.usb-quirks

### ISSUE THREAD

**Issue by mj-64** [apple/cups#5917]
My printer, a Samsung ML-1640 black and white laser printer does not work with the supplied /usr/share/cups/usb/org.cups.usb-quirks file. It contains "soft-reset" for all Samsung USB printers and that does not work with mine. Changing it to "unidir" works, though.

But this file will be overwritten by any upgrade to the cups package on my Linux distro (Arch). As I understand the sources, one can add other quirks files in that directory, but there is no precedence of files, i.e. all "quirks" are just collected. So if I add another file, my settings will not take precedence over the distros settings.

I can change the location of the complete cups datadir using an environment variable, but that seems like overkill, I would have to copy all files in /usr/share/cups to another location and would have to sync them to changes in the package.

There should be a configuration option to set a location for quirks files or better, a precedence system where the user can supply files that overwrite package settings.

If that is not possible, maybe someone could modify /usr/share/cups/usb/org.cups.usb-quirks

printer: Samsung Electronics Co., Ltd ML-1640 Series Laser Printer 
USB major.minor: 04e8:3292

Does not work with: soft-reset
Does work with: unidir

**Comment by michaelrsweet** [comment]
@mj-64 First, please report this over on the [OpenPrinting CUPS](https://github.com/OpenPrinting/cups) project as the Apple CUPS project is no longer being used for Linux.

Second, while there is no precedence to the loading of files, a vendor definition (like "all Samsung printers with VID 04E8) is always overridden by a produce definition (where both the vendor ID and product ID are specified). What happens when there are two files defining the same VID or PID is undefined. It sounds like adding a specific quirk for your printer will be sufficient in this case.

**Comment by mj-64** [comment]
Sorry, I wasn't aware that there are two cups projects, I just searched for cups and this one came up first. The more you know..

I just tried to create a file in /usr/share/cups/usb with the settings for my printer and it works! The specific entry seems to take precedence over the general Samsung one in org.cups.usb-quirks.

Thank you for your help and quick reply!
