### ISSUE TITLE
sudo make install: Operation not permitted

### ISSUE THREAD

**Issue by ggmartins** [apple/cups#5932]
Dear,

appreciate your work on cups. I had trouble installing printers from my company's server.
the error is always the same:
```
$ cupsctl 
cupsctl: Unable to connect to server: Bad file descriptor
```

after downloading cups and making from source* I have the following:
```
sudo make install
Making all in cups...
Installing data files in cups...
Installing data files in tools...
Installing data files in filter...
Installing data files in backend...
Installing data files in berkeley...
Installing data files in cgi-bin...
Installing data files in monitor...
Installing data files in notifier...
Installing data files in ppdc...
cp: /usr/share/cups/drv/#inst.7597#: Operation not permitted
make[1]: *** [install-data] Error 1
make: *** [install-data] Error 1
```
no clue about what's going on, please let me know if there's anything I can try.

(*) FYI several deprecated warnings :
```
./tls-darwin.c:445:17: warning: 'SSLCopyPeerTrust' is deprecated: first deprecated in macOS 10.15 - No longer supported. Use Network.framework. [-Wdeprecated-declarations]
  if (!(error = SSLCopyPeerTrust(http->tls, &peerTrust)) && peerTrust)
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecureTransport.h:1261:1: note: 'SSLCopyPeerTrust' has been explicitly marked deprecated here
SSLCopyPeerTrust                        (SSLContextRef          context,
```

thanks for any help.

**Comment by michaelrsweet** [comment]
@ggmartins OK, please read the INSTALL.md file. You cannot simply install a new copy of CUPS on top of macOS without first disabling System Integrity Protection (which coincidentally makes your system significantly less secure...) Also, be prepared for random issues caused by software updates overwriting your local changes.

However, if you are having trouble with `cupsctl` not being able to connect to `cupsd`, best thing is to contact AppleCare support in order to get a proper resolution.
